name: fus-detectors
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.*
  - scikit-learn
  - numba
  - pytorch=2.1.*
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyyaml
  - pip
  - pip:
      - k-Wave-python==0.4.0
      - PyMUST==0.1.9
      - scipy==1.14.1
      - matplotlib==3.10.0
      - scikit-image==0.25.2
      - h5py==3.12.1
      - imageio==2.37.3
      - opencv-python==4.10.0.84
      - rich
      - tqdm
      - hydra-core
      - pyyaml
      - plotly
      - pre-commit
      - ruff
      - black
      - pytest
      - pytest-cov
      - mypy
      - jupyterlab
      - ipykernel
