#!/usr/bin/env python3
"""
Brain-* detector ablation table: isolate whitening vs band selectivity.

This script summarizes strict-tail operating points for a small set of detector
variants evaluated on identical Brain-* k-Wave windows:

  1) PD on the MC--SVD residual (baseline score)
  2) Whitened total power (no Doppler band partition; "whitened PD" ablation)
  3) Unwhitened matched-subspace ratio (no whitening; "no-STAP" ablation)
  4) Full STAP score (whitened matched-subspace ratio; pre-KA)

It reads per-window rows from scripts/fair_filter_comparison.py (matrix mode)
and reports medians (IQR) over the five disjoint 64-frame windows.

Outputs (tracked):
  - reports/brain_detector_ablation.csv
  - reports/brain_detector_ablation.json
  - reports/brain_detector_ablation_table.tex
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


def _finite(vals: Iterable[float]) -> np.ndarray:
    v = np.asarray(list(vals), dtype=np.float64)
    return v[np.isfinite(v)]


def _quantile_summary(vals: Iterable[float]) -> tuple[float, float, float]:
    v = _finite(vals)
    if v.size <= 0:
        return float("nan"), float("nan"), float("nan")
    med = float(np.quantile(v, 0.5))
    q25 = float(np.quantile(v, 0.25))
    q75 = float(np.quantile(v, 0.75))
    return med, q25, q75


def _fmt_cell(med: float, q25: float, q75: float) -> str:
    if not (np.isfinite(med) and np.isfinite(q25) and np.isfinite(q75)):
        return "n/a"
    return f"{med:.4f} ({q25:.4f},{q75:.4f})"


@dataclass(frozen=True)
class Cell:
    regime: str
    method: str
    fpr: float
    n_windows: int
    tpr_med: float
    tpr_q25: float
    tpr_q75: float


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--fair-matrix-json",
        type=Path,
        default=Path("reports/fair_matrix_detector_ablations.json"),
        help="Input fair-matrix JSON (list of per-window rows).",
    )
    ap.add_argument(
        "--fprs",
        type=float,
        nargs="+",
        default=[1e-4, 3e-4, 1e-3],
        help="Strict-tail FPR targets to tabulate (default: 1e-4 3e-4 1e-3).",
    )
    ap.add_argument(
        "--out-csv",
        type=Path,
        default=Path("reports/brain_detector_ablation.csv"),
        help="Output CSV path (default: %(default)s).",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=Path("reports/brain_detector_ablation.json"),
        help="Output JSON path (default: %(default)s).",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/brain_detector_ablation_table.tex"),
        help="Output LaTeX table path (default: %(default)s).",
    )
    return ap.parse_args()


def _method_order() -> list[str]:
    return [
        "MC-SVD",
        "Detector ablation: whitened power (no band)",
        "Detector ablation: unwhitened ratio (no whitening)",
        "STAP (MC-SVD+STAP, full)",
    ]


def _method_display() -> dict[str, str]:
    return {
        "MC-SVD": "PD on MC--SVD residual",
        "Detector ablation: whitened power (no band)": "Whitened power (no band)",
        "Detector ablation: unwhitened ratio (no whitening)": "Unwhitened ratio (no whitening)",
        "STAP (MC-SVD+STAP, full)": "STAP (whitened ratio; pre-KA)",
    }


def _regime_order() -> list[tuple[str, str]]:
    return [
        ("open", "OpenSkull"),
        ("aliascontract", "AliasContract"),
        ("skullor", "SkullOR"),
    ]


def _render_table_tex(
    *,
    out_path: Path,
    cell_map: dict[tuple[str, str, float], tuple[float, float, float]],
    methods: list[str],
    method_display: dict[str, str],
    regimes: list[tuple[str, str]],
    fprs: list[float],
) -> None:
    def _cell(regime_key: str, method: str, fpr: float) -> str:
        stats = cell_map.get((regime_key, method, float(fpr)))
        if stats is None:
            return "n/a"
        return _fmt_cell(*stats)

    def _alpha_tex(a: float) -> str:
        a = float(a)
        if a > 0.0 and np.isfinite(a):
            for k in range(0, 12):
                m = a * (10.0**k)
                m_round = round(m)
                if abs(m - m_round) <= 1e-12 and 1 <= m_round < 10 and k > 0:
                    if int(m_round) == 1:
                        return f"10^{{-{int(k)}}}"
                    return f"{int(m_round)}\\!\\times\\!10^{{-{int(k)}}}"
        return f"{a:g}"

    cols = "l" + (("c" * len(fprs)) + " ") * len(regimes)
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/brain_detector_ablation_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append(f"\\begin{{tabular}}{{@{{}}{cols.strip()}@{{}}}}")
    lines.append("\\hline")

    # Header row: regimes
    header = ["Method"]
    for _, display in regimes:
        header.append(f"\\multicolumn{{{len(fprs)}}}{{c}}{{{display}}}")
    lines.append(" & ".join(header) + " \\\\")
    start = 2
    clines: list[str] = []
    for _ in regimes:
        end = start + len(fprs) - 1
        clines.append(f"\\cline{{{start}-{end}}}")
        start = end + 1
    lines.append(" ".join(clines))

    # Sub-header: alpha columns
    sub = [" "]
    for _ in regimes:
        sub += [f"$\\alpha={_alpha_tex(a)}$" for a in fprs]
    lines.append(" & ".join(sub) + " \\\\")
    lines.append("\\hline")

    for method in methods:
        row = [method_display.get(method, method)]
        for regime_key, _ in regimes:
            for a in fprs:
                row.append(_cell(regime_key, method, float(a)))
        lines.append(" & ".join(row) + " \\\\")

    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Detector ablations on Brain-* regimes (MC--SVD residual, fixed profile). "
        "All rows share the identical MC--SVD residual cube and differ only in the detector statistic: "
        "baseline PD, total power after tile-local whitening (no Doppler band partition), "
        "matched-subspace ratio without whitening (R=I), and the full STAP whitened matched-subspace ratio. "
        "Numbers are medians (IQR) over five disjoint 64-frame windows (offsets 0/64/128/192/256).}"
    )
    lines.append("\\label{tab:brain_detector_ablation}")
    lines.append("\\end{table}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows = json.loads(args.fair_matrix_json.read_text(encoding="utf-8"))
    if not isinstance(rows, list):
        raise ValueError("Expected fair-matrix JSON to be a list of rows.")

    fprs = [float(x) for x in args.fprs]
    methods = _method_order()
    method_display = _method_display()
    regimes = _regime_order()

    # (regime, method, fpr) -> [tpr values]
    buckets: dict[tuple[str, str, float], list[float]] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        regime = str(row.get("regime", "")).strip()
        method = str(row.get("method", "")).strip()
        if not regime or not method:
            continue
        for fpr in fprs:
            key_tpr = f"tpr@{float(fpr):g}"
            # fair_filter_comparison stores keys like tpr@0.0001 / tpr@0.0003 / tpr@0.001
            # so we try a few stable renderings.
            cand_keys = [
                f"tpr@{fpr}",
                f"tpr@{float(fpr)}",
                f"tpr@{float(fpr):.4f}",
                f"tpr@{float(fpr):.4g}",
                key_tpr,
            ]
            tpr_val = None
            for ck in cand_keys:
                if ck in row:
                    tpr_val = row.get(ck)
                    break
            if tpr_val is None:
                continue
            try:
                tpr = float(tpr_val)
            except (TypeError, ValueError):
                continue
            buckets.setdefault((regime, method, float(fpr)), []).append(tpr)

    cells: list[Cell] = []
    cell_map: dict[tuple[str, str, float], tuple[float, float, float]] = {}
    for regime_key, _ in regimes:
        for method in methods:
            for fpr in fprs:
                vals = buckets.get((regime_key, method, float(fpr)), [])
                med, q25, q75 = _quantile_summary(vals)
                cells.append(
                    Cell(
                        regime=str(regime_key),
                        method=str(method),
                        fpr=float(fpr),
                        n_windows=int(len(vals)),
                        tpr_med=float(med),
                        tpr_q25=float(q25),
                        tpr_q75=float(q75),
                    )
                )
                cell_map[(regime_key, method, float(fpr))] = (med, q25, q75)

    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(
        json.dumps([asdict(c) for c in cells], indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    with open(args.out_csv, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(asdict(cells[0]).keys()))
        writer.writeheader()
        for c in cells:
            writer.writerow(asdict(c))

    _render_table_tex(
        out_path=args.out_tex,
        cell_map=cell_map,
        methods=methods,
        method_display=method_display,
        regimes=regimes,
        fprs=fprs,
    )


if __name__ == "__main__":
    main()
