#!/usr/bin/env python3
"""
Brain-* detector-swap table: apply the same matched-subspace STAP detector score
to residuals produced by competing clutter filters (e.g., RPCA/HOSVD).

Motivation
----------
Addresses the reviewer concern that strict-tail failures of PD-after-filter
baselines (TPR≈0 at alpha∈[1e-4,1e-3]) could reflect weak baseline tuning or
implementation mistakes. By re-scoring *the same residual* with the STAP
matched-subspace statistic, we isolate "detector vs clutter suppression".

Inputs
------
`reports/fair_matrix_detector_swap.json` produced by:
  PYTHONPATH=. conda run -n stap-fus python scripts/fair_filter_comparison.py --mode matrix ...

Outputs (tracked)
-----------------
  - reports/brain_detector_swap.csv
  - reports/brain_detector_swap.json
  - reports/brain_detector_swap_table.tex
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np


def _finite(vals: Iterable[float]) -> np.ndarray:
    v = np.asarray(list(vals), dtype=np.float64)
    return v[np.isfinite(v)]


def _quantile_summary(vals: Iterable[float]) -> tuple[float, float, float]:
    v = _finite(vals)
    if v.size <= 0:
        return float("nan"), float("nan"), float("nan")
    med = float(np.quantile(v, 0.5))
    q25 = float(np.quantile(v, 0.25))
    q75 = float(np.quantile(v, 0.75))
    return med, q25, q75


def _fmt_cell(med: float, q25: float, q75: float) -> str:
    if not (np.isfinite(med) and np.isfinite(q25) and np.isfinite(q75)):
        return "n/a"
    return f"{med:.4f} ({q25:.4f},{q75:.4f})"


@dataclass(frozen=True)
class Cell:
    regime: str
    method: str
    fpr: float
    n_windows: int
    tpr_med: float
    tpr_q25: float
    tpr_q75: float


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--fair-matrix-json",
        type=Path,
        default=Path("reports/fair_matrix_detector_swap.json"),
        help="Input matrix JSON (list of per-window rows).",
    )
    ap.add_argument(
        "--fprs",
        type=float,
        nargs="+",
        default=[1e-4, 3e-4, 1e-3],
        help="Strict-tail FPR targets to tabulate (default: 1e-4 3e-4 1e-3).",
    )
    ap.add_argument(
        "--out-csv",
        type=Path,
        default=Path("reports/brain_detector_swap.csv"),
        help="Output CSV path (default: %(default)s).",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=Path("reports/brain_detector_swap.json"),
        help="Output JSON path (default: %(default)s).",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/brain_detector_swap_table.tex"),
        help="Output LaTeX table path (default: %(default)s).",
    )
    return ap.parse_args()


def _method_order() -> list[str]:
    return [
        "RPCA+PD (paired)",
        "RPCA+STAP (paired; pre-KA)",
        "HOSVD+PD (paired)",
        "HOSVD+STAP (paired; pre-KA)",
    ]


def _regime_order() -> list[tuple[str, str]]:
    return [
        ("open", "\\shortstack{Open-skull surface-\\\\artifact stress test}"),
        ("skullor", "\\shortstack{Structured-clutter\\\\leakage stress test}"),
    ]


def _method_display() -> dict[str, str]:
    return {
        "RPCA+PD (paired)": "PD on RPCA residual",
        "RPCA+STAP (paired; pre-KA)": "Matched-subspace detector on RPCA residual",
        "HOSVD+PD (paired)": "PD on HOSVD residual",
        "HOSVD+STAP (paired; pre-KA)": "Matched-subspace detector on HOSVD residual",
    }


def _render_table_tex(
    *,
    out_path: Path,
    cell_map: dict[tuple[str, str, float], tuple[float, float, float]],
    methods: list[str],
    method_display: dict[str, str],
    regimes: list[tuple[str, str]],
    fprs: list[float],
) -> None:
    def _cell(regime_key: str, method: str, fpr: float) -> str:
        stats = cell_map.get((regime_key, method, float(fpr)))
        if stats is None:
            return "n/a"
        return _fmt_cell(*stats)

    def _alpha_tex(a: float) -> str:
        a = float(a)
        if a > 0.0 and np.isfinite(a):
            # Prefer compact scientific forms (e.g., 1e-3 -> 10^{-3},
            # 3e-4 -> 3×10^{-4}) to match the manuscript tables.
            for k in range(0, 12):
                m = a * (10.0**k)
                m_round = round(m)
                if abs(m - m_round) <= 1e-12 and 1 <= m_round < 10 and k > 0:
                    if int(m_round) == 1:
                        return f"10^{{-{int(k)}}}"
                    return f"{int(m_round)}\\!\\times\\!10^{{-{int(k)}}}"
        return f"{a:g}"

    cols = "l" + (("c" * len(fprs)) + " ") * len(regimes)
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/brain_detector_swap_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append(f"\\begin{{tabular}}{{@{{}}{cols.strip()}@{{}}}}")
    lines.append("\\hline")

    # Header row: regimes
    header = ["Method"]
    for _, display in regimes:
        header.append(f"\\multicolumn{{{len(fprs)}}}{{c}}{{{display}}}")
    lines.append(" & ".join(header) + " \\\\")
    start = 2
    clines: list[str] = []
    for _ in regimes:
        end = start + len(fprs) - 1
        clines.append(f"\\cline{{{start}-{end}}}")
        start = end + 1
    lines.append(" ".join(clines))

    # Sub-header: alpha columns
    sub = [" "]
    for _ in regimes:
        sub += [f"$\\alpha={_alpha_tex(a)}$" for a in fprs]
    lines.append(" & ".join(sub) + " \\\\")
    lines.append("\\hline")

    for method in methods:
        row = [method_display.get(method, method)]
        for regime_key, _ in regimes:
            for a in fprs:
                row.append(_cell(regime_key, method, float(a)))
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Detector-swap fairness check on labeled brain simulation stress tests: PD vs matched-subspace detector scores "
        "computed on the \\emph{same} residual produced by a competing clutter filter (paired bundles). "
        "The two column groups correspond to an open-skull surface-artifact stress test and a structured-clutter leakage stress test. "
        "Numbers are medians (IQR) over five disjoint 64-frame windows (offsets 0/64/128/192/256).}"
    )
    lines.append("\\label{tab:brain_detector_swap}")
    lines.append("\\end{table}")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    rows: list[dict[str, Any]] = json.loads(args.fair_matrix_json.read_text(encoding="utf-8"))
    fprs = [float(x) for x in args.fprs]
    methods = _method_order()
    method_display = _method_display()
    regimes = _regime_order()

    # Collect per-window TPRs.
    tpr_by_key: dict[tuple[str, str, float], list[float]] = {}
    for row in rows:
        regime = str(row.get("regime") or "")
        method = str(row.get("method") or "")
        if method not in methods:
            continue
        if regime not in {r for r, _ in regimes}:
            continue
        for a in fprs:
            k = f"tpr@{a:g}"
            if k not in row:
                continue
            try:
                tpr = float(row[k])
            except (TypeError, ValueError):
                continue
            tpr_by_key.setdefault((regime, method, float(a)), []).append(tpr)

    # Summarize cells.
    cells: list[Cell] = []
    cell_map: dict[tuple[str, str, float], tuple[float, float, float]] = {}
    for regime_key, _ in regimes:
        for method in methods:
            for a in fprs:
                vals = tpr_by_key.get((regime_key, method, float(a)), [])
                med, q25, q75 = _quantile_summary(vals)
                cell_map[(regime_key, method, float(a))] = (med, q25, q75)
                cells.append(
                    Cell(
                        regime=regime_key,
                        method=method,
                        fpr=float(a),
                        n_windows=int(len(vals)),
                        tpr_med=float(med),
                        tpr_q25=float(q25),
                        tpr_q75=float(q75),
                    )
                )

    # Write CSV/JSON.
    args.out_csv.parent.mkdir(parents=True, exist_ok=True)
    with args.out_csv.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(asdict(cells[0]).keys()))
        writer.writeheader()
        for c in cells:
            writer.writerow(asdict(c))
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps([asdict(c) for c in cells], indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # Write LaTeX table.
    _render_table_tex(
        out_path=args.out_tex,
        cell_map=cell_map,
        methods=methods,
        method_display=method_display,
        regimes=regimes,
        fprs=fprs,
    )
    print(f"[brain_detector_swap_table] wrote {args.out_csv}, {args.out_json}, {args.out_tex}")


if __name__ == "__main__":
    main()
