#!/usr/bin/env python3
"""
Generate the Brain-* low-FPR baseline table (vnext) from the fair-matrix JSON.

This script exists to make Table `tab:brain_kwave_vnext_baselines` fully
reproducible (no manual copy/paste of numbers into LaTeX).

Inputs:
  - reports/fair_matrix_vnext_r3_localbaselines.json (list of per-window records)

Outputs:
  - reports/brain_kwave_vnext_baselines_table.tex (LaTeX table environment)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def _parse_csv_floats(s: str) -> list[float]:
    out: list[float] = []
    for tok in (s or "").split(","):
        tok = tok.strip()
        if not tok:
            continue
        out.append(float(tok))
    return out


def _q(v: list[float], q: float) -> float:
    if not v:
        return float("nan")
    return float(np.quantile(np.asarray(v, dtype=np.float64), q))


def _fmt_cell(med: float, q25: float, q75: float) -> str:
    if not (np.isfinite(med) and np.isfinite(q25) and np.isfinite(q75)):
        return r"\textemdash"
    if abs(med) < 5e-7 and abs(q25) < 5e-7 and abs(q75) < 5e-7:
        return "0"
    return f"{med:.3f} ({q25:.3f},{q75:.3f})"


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--fair-matrix-json",
        type=Path,
        default=Path("reports/fair_matrix_vnext_r3_localbaselines.json"),
        help="Input fair-matrix JSON (list of per-window records).",
    )
    ap.add_argument(
        "--alphas",
        type=str,
        default="1e-4,3e-4,1e-3",
        help="Comma-separated FPR targets to tabulate (must match JSON keys).",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/brain_kwave_vnext_baselines_table.tex"),
        help="Output LaTeX table path.",
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    records = json.loads(Path(args.fair_matrix_json).read_text())
    if not isinstance(records, list):
        raise SystemExit(f"Expected list JSON: {args.fair_matrix_json}")

    alphas = _parse_csv_floats(args.alphas)
    alpha_fields = {a: f"tpr@{format(float(a), 'g')}" for a in alphas}

    # Canonical regime/method ordering used in the main paper.
    regime_order = ["open", "aliascontract", "skullor"]
    regime_title = {
        "open": "Brain-OpenSkull",
        "aliascontract": "Brain-AliasContract",
        "skullor": "Brain-SkullOR",
    }
    method_order = [
        "MC-SVD",
        "Adaptive SVD (similarity cutoff)",
        "Local SVD (block-wise)",
        "RPCA",
        "HOSVD",
        "STAP (MC-SVD+STAP, full)",
    ]
    method_label = {
        "MC-SVD": r"MC--SVD",
        "Adaptive SVD (similarity cutoff)": r"Adaptive SVD (spatial singular-vector similarity cutoff)",
        "Local SVD (block-wise)": r"Block-wise local SVD (overlap-add)",
        "RPCA": r"RPCA",
        "HOSVD": r"HOSVD",
        "STAP (MC-SVD+STAP, full)": r"Matched-subspace detector on MC--SVD residual",
    }

    have_regimes = sorted({str(r.get("regime")) for r in records if isinstance(r, dict)})
    for rg in regime_order:
        if rg not in have_regimes:
            raise SystemExit(
                f"Missing expected regime {rg!r} in {args.fair_matrix_json}; have {have_regimes}"
            )

    have_methods = sorted({str(r.get("method")) for r in records if isinstance(r, dict)})
    for m in method_order:
        if m not in have_methods:
            raise SystemExit(
                f"Missing expected method {m!r} in {args.fair_matrix_json}; have {have_methods}"
            )

    def _gather(method: str, regime: str, field: str) -> list[float]:
        vals: list[float] = []
        for r in records:
            if not isinstance(r, dict):
                continue
            if str(r.get("method")) != method:
                continue
            if str(r.get("regime")) != regime:
                continue
            v = r.get(field)
            if v is None:
                continue
            try:
                vals.append(float(v))
            except Exception:
                continue
        return vals

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/brain_kwave_vnext_baselines_table.py; DO NOT EDIT BY HAND.")
    lines.append(r"\begin{table}[t]")
    lines.append(r"\centering")
    lines.append(r"\small")
    lines.append(r"\resizebox{\linewidth}{!}{%")
    lines.append(r"\begin{tabular}{lccc ccc ccc}")
    lines.append(r"\hline")
    lines.append(
        " & "
        + " & ".join(rf"\multicolumn{{3}}{{c}}{{{regime_title[rg]}}}" for rg in regime_order)
        + r" \\"
    )
    alpha_hdr = r"Method / score & " + " & ".join(
        [r"TPR@$10^{-4}$", r"TPR@$3\!\times\!10^{-4}$", r"TPR@$10^{-3}$"] * 3
    )
    lines.append(alpha_hdr + r" \\")
    lines.append(r"\hline")

    for method in method_order:
        row = [method_label.get(method, method)]
        for rg in regime_order:
            for a in alphas:
                field = alpha_fields[float(a)]
                vals = _gather(method, rg, field)
                med = _q(vals, 0.5)
                q25 = _q(vals, 0.25)
                q75 = _q(vals, 0.75)
                row.append(_fmt_cell(med, q25, q75))
        lines.append(" & ".join(row) + r" \\")

    lines.append(r"\hline")
    lines.append(r"\end{tabular}")
    lines.append(r"}")
    lines.append(
        r"\caption{Brain-* k-Wave low-FPR operating points using flow-evidence detection scores (higher = more likely flow): baseline power Doppler and the matched-subspace detector. Each regime uses five non-overlapping 64-frame windows (offsets 0/64/128/192/256); each window has $n_{\mathrm{neg}}=50199$ ($fpr_{\min}\approx 1.99\times 10^{-5}$). At this support, FPR targets $10^{-4}$, $3\!\times\!10^{-4}$, and $10^{-3}$ correspond to approximately 5, 15, and 50 false-positive pixels per window. Entries report median (IQR) TPR across windows at each target FPR. Cells shown as 0 indicate no measurable sensitivity at that supported operating point. Baselines compare clutter suppression strategies (MC--SVD; adaptive SVD with a spatial singular-vector similarity cutoff; block-wise local SVD with overlap-add; RPCA; HOSVD) and are scored by power Doppler; the matched-subspace detector is applied on top of the MC--SVD residual.}"
    )
    lines.append(r"\label{tab:brain_kwave_vnext_baselines}")
    lines.append(r"\end{table}")
    lines.append("")

    out_path = Path(args.out_tex)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[brain_kwave_table] wrote {out_path}")


if __name__ == "__main__":
    main()
