#!/usr/bin/env python3
"""
Render a compact LaTeX table for the labeled-brain robust-whitening stability audit.

Input:
  reports/brain_whitening_policy_validation_huber_trim_sensitivity.csv

Output:
  reports/paper/brain_huber_trim_stability_table.tex
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


REGIMES = (
    ("open", "Open-skull stress test"),
    ("skullor", "Structured-clutter stress test"),
)
CONFIGS = (
    ("huber_trim5", "$q=0.05$"),
    ("huber_trim8", "$q=0.08$"),
    ("huber_trim10", "$q=0.10$"),
)
SPLITS = ("within", "cross", "fixed_cal")
ALPHA = "0.0001"


def _fmt_tpr(val: float) -> str:
    return f"{val:.3f}"


def _fmt_fpr(med: float, q75: float) -> str:
    return f"{med:.2e} ({q75:.2e})"


def _load_rows(path: Path) -> dict[tuple[str, str, str, str], dict[str, float]]:
    out: dict[tuple[str, str, str, str], dict[str, float]] = {}
    with path.open(newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            key = (row["regime"], row["config"], row["split"], row["alpha"])
            out[key] = {k: float(v) for k, v in row.items() if k not in {"regime", "regime_label", "config", "split", "alpha"}}
    return out


def _render_table(rows: dict[tuple[str, str, str, str], dict[str, float]]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/brain_huber_trim_stability_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{@{}lccc ccc@{}}")
    lines.append("\\hline")
    lines.append("Trim setting & \\multicolumn{3}{c}{Open-skull stress test} & \\multicolumn{3}{c}{Structured-clutter stress test} \\\\")
    lines.append("\\cline{2-4} \\cline{5-7}")
    lines.append(" & Within TPR@$10^{-4}$ & Cross FPR med. (q75) & Fixed-cal FPR med. (q75) & Within TPR@$10^{-4}$ & Cross FPR med. (q75) & Fixed-cal FPR med. (q75) \\\\")
    lines.append("\\hline")
    for config_key, config_label in CONFIGS:
        cells = [config_label]
        for regime_key, _ in REGIMES:
            within = rows[(regime_key, config_key, "within", ALPHA)]
            cross = rows[(regime_key, config_key, "cross", ALPHA)]
            fixed_cal = rows[(regime_key, config_key, "fixed_cal", ALPHA)]
            cells.append(_fmt_tpr(within["tpr_median"]))
            cells.append(_fmt_fpr(cross["fpr_median"], cross["fpr_q75"]))
            cells.append(_fmt_fpr(fixed_cal["fpr_median"], fixed_cal["fpr_q75"]))
        lines.append(" & ".join(cells) + " \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Robust-whitening stability audit for the prespecified fully whitened detector on the labeled brain stress tests. "
        "The only changing parameter is the high-energy covariance-training trim $q$. "
        "Entries report within-window TPR at the strictest operating point ($\\alpha=10^{-4}$) together with realized FPR under pairwise cross-window transfer and a leave-one-window-out fixed calibration bank. "
        "The reported values are numerically unchanged across $q\\in\\{0.05,0.08,0.10\\}$, indicating that the finalized advanced recipe is stable to modest covariance-training trim variation in these stress tests.}"
    )
    lines.append("\\label{tab:brain_huber_trim_stability}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--in-csv",
        type=Path,
        default=Path("reports/brain_whitening_policy_validation_huber_trim_sensitivity.csv"),
        help="Input CSV from brain_whitening_policy_validation.py.",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/paper/brain_huber_trim_stability_table.tex"),
        help="Output LaTeX table fragment path.",
    )
    args = ap.parse_args()

    rows = _load_rows(args.in_csv)
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(_render_table(rows), encoding="utf-8")


if __name__ == "__main__":
    main()
