#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _build_tex(rows: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/detector_family_policy_summary.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\footnotesize")
    lines.append("\\setlength{\\tabcolsep}{3pt}")
    lines.append("\\renewcommand{\\arraystretch}{1.08}")
    lines.append("\\begin{tabular}{@{}P{3.9cm} P{2.7cm} P{4.1cm} P{4.2cm}@{}}")
    lines.append("\\hline")
    lines.append("Regime / endpoint & Recommended head & Why & Evidence \\\\")
    lines.append("\\hline")
    for row in rows:
        lines.append(
            f"{row['regime_tex']} & {row['head_tex']} & {row['why_tex']} & {row['evidence_tex']} \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Operational detector-family policy implied by the main-text evidence. The paper does not support "
        "one universal winner. Instead it supports a fixed default for the held-out structural benchmark, an adaptive "
        "hedge when one deployable score must preserve fixed-head behavior in cleaner settings without abandoning "
        "whitening entirely, and a fully whitened specialist for regimes in which covariance adaptation clearly earns "
        "its complexity.}"
    )
    lines.append("\\label{tab:detector_family_policy}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    rows: list[dict[str, Any]] = []
    rows.append(
        {
            "regime_tex": "SIMUS mobile / intra-op -- simulated labels -- nuisance-control ROC",
            "head_tex": "Fixed matched-subspace detector",
            "why_tex": "Best fixed downstream head on the prespecified held-out structural benchmark and on the same-residual MC--SVD ablation.",
            "evidence_tex": "Tables~\\ref{tab:accepted_v2_structural_main} and \\ref{tab:simus_detector_family_ablation}.",
        }
    )
    rows.append(
        {
            "regime_tex": "One deployable head under mixed clutter burden",
            "head_tex": "Adaptive detector",
            "why_tex": "Matches the fixed head on cleaner residuals and only promotes clutter-heavy tiles to whitening when the guard statistic fires.",
            "evidence_tex": "Same-residual SIMUS rows collapse to the fixed head; the same frozen rule is retained for harsher audits and real-IQ use.",
        }
    )
    rows.append(
        {
            "regime_tex": "SIMUS held-out stress regime -- cardiac pulsation and short ensembles",
            "head_tex": "Fully whitened specialist",
            "why_tex": "Strongest on the cardiac rows and on the 64-frame and 48-frame short-ensemble rows; fixed remains strongest only on the hardest 32-frame row.",
            "evidence_tex": "Tables~\\ref{tab:simus_stress_frontier_headline} and \\ref{tab:simus_stress_frontier_rpca_heads}.",
        }
    )
    rows.append(
        {
            "regime_tex": "ULM 7883227 -- localization-derived structure labels -- vessel-core ROC",
            "head_tex": "Fully whitened specialist",
            "why_tex": "Only head that improves pooled AUC, strict-tail sensitivity, and shell suppression together on the same residual cube.",
            "evidence_tex": "Tables~\\ref{tab:ulm7883227_structural_roc} and \\ref{tab:ulm_fixed_calibration_transfer}.",
        }
    )

    payload = {
        "schema_version": "detector_family_policy_summary.v2",
        "rows": rows,
    }
    _write_json(Path("reports/detector_family_policy_summary.json"), payload)
    _write_csv(Path("reports/detector_family_policy_summary.csv"), rows)
    Path("reports/detector_family_policy_table.tex").write_text(_build_tex(rows), encoding="utf-8")


if __name__ == "__main__":
    main()
