#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _fmt3(x: float) -> str:
    return f"{float(x):.3f}"


def _fmt_winloss(wins: int, losses: int) -> str:
    return f"{int(wins)}/{int(wins + losses)}"


def _build_tex(rows: list[dict[str, Any]]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/detector_family_policy_summary.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{@{}P{3.0cm} P{2.7cm} P{3.9cm} P{5.8cm}@{}}")
    lines.append("\\hline")
    lines.append("Evidence regime & Preferred head & Quantitative anchor & Practical interpretation \\\\")
    lines.append("\\hline")
    for row in rows:
        lines.append(
            f"{row['regime']} & {row['preferred_head_tex']} & {row['anchor_tex']} & {row['interpretation_tex']} \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Detector-family policy implied by the current evidence. The simpler band-limited "
        "matched-subspace detector is the fixed deployed default because it remains strongest on the prespecified "
        "held-out structural benchmark across all tested fixed profiles. The frozen guard-triggered adaptive mode "
        "is the adaptive deployment product because it preserves the fixed-head "
        "behavior in cleaner regimes while selectively turning on whitening in clutter-heavier ones. The fully "
        "whitened STAP-inspired mode is retained as a specialist setting where full whitening still earns its "
        "complexity.}"
    )
    lines.append("\\label{tab:detector_family_policy}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    structural = _load_json(Path("reports/simus_v2/simus_structural_candidate_profile_compare.json"))
    twinkling = _load_json(Path("reports/stap_covariance_regime_sweep_huber_shortlist_twinkling.json"))
    functional = _load_json(Path("reports/simus_v2/simus_functional_candidate_compare_eval_summary.json"))
    adaptive_guard = _load_json(Path("reports/adaptive_guard_refine.json"))

    structural_best = {row["setting"]: row for row in structural["best_profile_by_setting_for_huber_trim8"]}

    gammex_rows = twinkling["summary"]["twinkling"]["Gammex across-view"]
    gammex_by_cfg = {row["config"]: row for row in gammex_rows}
    gammex_u = gammex_by_cfg["unwhitened_ref"]
    gammex_h = gammex_by_cfg["huber_trim8"]

    adaptive_row = next(
        row for row in adaptive_guard["rows"] if float(row["guard_hi"]) == float(adaptive_guard["selected_threshold"])
    )
    adaptive_sc = adaptive_row["scenarios"]

    func_comp = functional["comparison"]
    func_groups: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for row in func_comp:
        key = (str(row["base_profile"]), str(row["detector_head"]))
        func_groups.setdefault(key, []).append(row)
    mobile_stap = func_groups[("ClinMobile-Pf-v2", "stap")]
    mobile_stap_pd = func_groups[("ClinMobile-Pf-v2", "stap_pd")]
    intra_stap = func_groups[("ClinIntraOpParenchyma-Pf-v3", "stap")]
    intra_stap_pd = func_groups[("ClinIntraOpParenchyma-Pf-v3", "stap_pd")]

    rows: list[dict[str, Any]] = []
    rows.append(
        {
            "regime": "Prespecified held-out structural benchmark (mobile and intra-operative parenchymal)",
            "preferred_head": "unwhitened_ref",
            "preferred_head_tex": "Fixed band-limited matched-subspace head ($R=I$)",
            "anchor": (
                "Best tested fixed profile for whitening still gives "
                f"Delta-selection={_fmt3(structural_best['Mobile']['mean_delta_selection_huber_minus_unwhitened'])} "
                "on Mobile and "
                f"{_fmt3(structural_best['Intra-operative parenchymal']['mean_delta_selection_huber_minus_unwhitened'])} "
                "on intra-operative parenchyma"
            ),
            "anchor_tex": (
                "Best whitening profile still trails the default: "
                f"$\\Delta$selection={_fmt3(structural_best['Mobile']['mean_delta_selection_huber_minus_unwhitened'])} "
                "(mobile) and "
                f"{_fmt3(structural_best['Intra-operative parenchymal']['mean_delta_selection_huber_minus_unwhitened'])} "
                "(intra-operative parenchyma)"
            ),
            "interpretation": "Use the simpler head as the default translational choice.",
            "interpretation_tex": "Use the simpler head as the default translational choice.",
        }
    )
    rows.append(
        {
            "regime": "Frozen adaptive deployment mode across labeled/open audits",
            "preferred_head": "adaptive_guard",
            "preferred_head_tex": "Guard-triggered adaptive mode",
            "anchor": (
                f"Open-skull / structured-clutter TPR@1e-4 stay at "
                f"{_fmt3(adaptive_sc['brain_open']['brain_tpr_alpha1e4'])} / "
                f"{_fmt3(adaptive_sc['brain_skullor']['brain_tpr_alpha1e4'])}; "
                f"mean promoted fraction = {_fmt3(adaptive_sc['shin']['mean_whiten_fraction'])} on Shin and "
                f"{_fmt3(adaptive_sc['across']['mean_whiten_fraction'])} on across-view Gammex"
            ),
            "anchor_tex": (
                f"Open-skull / structured-clutter TPR@$10^{{-4}}$ stay at "
                f"{_fmt3(adaptive_sc['brain_open']['brain_tpr_alpha1e4'])} / "
                f"{_fmt3(adaptive_sc['brain_skullor']['brain_tpr_alpha1e4'])}; "
                f"mean promoted fraction = {_fmt3(adaptive_sc['shin']['mean_whiten_fraction'])} (Shin) and "
                f"{_fmt3(adaptive_sc['across']['mean_whiten_fraction'])} (across-view Gammex)"
            ),
            "interpretation": "Preferred frozen adaptive product when one adaptive score is desired without abandoning the fixed-head behavior in cleaner regimes.",
            "interpretation_tex": "Preferred frozen adaptive product when one adaptive score is desired without abandoning the fixed-head behavior in cleaner regimes.",
        }
    )
    rows.append(
        {
            "regime": "Structurally labeled Gammex phantom (across-view)",
            "preferred_head": "msd_ratio_specialist",
            "preferred_head_tex": "Fully whitened specialist mode (\\texttt{msd\\_ratio})",
            "anchor": (
                f"TPR@1e-3: {_fmt3(gammex_u['tpr@1e-3_mean'])} -> {_fmt3(gammex_h['tpr@1e-3_mean'])}"
            ),
            "anchor_tex": (
                f"Across-view TPR@$10^{{-3}}$: {_fmt3(gammex_u['tpr@1e-3_mean'])} "
                f"$\\rightarrow$ {_fmt3(gammex_h['tpr@1e-3_mean'])}"
            ),
            "interpretation": "Use the fully whitened specialist when maximizing whitening gain matters more than preserving default-like behavior.",
            "interpretation_tex": "Use the fully whitened specialist when maximizing whitening gain matters more than preserving default-like behavior.",
        }
    )
    rows.append(
        {
            "regime": "Held-out same-residual functional audit",
            "preferred_head": "msd_ratio_specialist",
            "preferred_head_tex": "Fully whitened specialist mode (\\texttt{msd\\_ratio})",
            "anchor": (
                f"Positive in {_fmt_winloss(sum(float(r['delta_selection_b_minus_a']) > 0 for r in mobile_stap), sum(float(r['delta_selection_b_minus_a']) < 0 for r in mobile_stap))} "
                f"mobile families for direct STAP readout and {_fmt_winloss(sum(float(r['delta_selection_b_minus_a']) > 0 for r in intra_stap_pd), sum(float(r['delta_selection_b_minus_a']) < 0 for r in intra_stap_pd))} "
                f"intra-operative families for PD-after-STAP"
            ),
            "anchor_tex": (
                f"Positive in {_fmt_winloss(sum(float(r['delta_selection_b_minus_a']) > 0 for r in mobile_stap), sum(float(r['delta_selection_b_minus_a']) < 0 for r in mobile_stap))} "
                f"mobile families (direct STAP readout) and {_fmt_winloss(sum(float(r['delta_selection_b_minus_a']) > 0 for r in intra_stap_pd), sum(float(r['delta_selection_b_minus_a']) < 0 for r in intra_stap_pd))} "
                f"intra-operative families (PD-after-STAP)"
            ),
            "interpretation": "Keep the fully whitened specialist for function-priority audits even though it is not the structural default.",
            "interpretation_tex": "Keep the fully whitened specialist for function-priority audits even though it is not the structural default.",
        }
    )

    payload = {
        "schema_version": "detector_family_policy_summary.v1",
        "default_candidate": "unwhitened_ref",
        "adaptive_candidate": "adaptive_guard",
        "specialist_candidate": "msd_ratio/huber_trim8",
        "rows": rows,
    }
    _write_json(Path("reports/detector_family_policy_summary.json"), payload)
    _write_csv(Path("reports/detector_family_policy_summary.csv"), rows)
    Path("reports/detector_family_policy_table.tex").write_text(_build_tex(rows), encoding="utf-8")


if __name__ == "__main__":
    main()
