#!/usr/bin/env python3
"""
Phase 7: Reproducibility manifest generator (JSON + LaTeX appendix).

This script is intentionally *lightweight*: it does not rerun experiments.
Instead it produces a pinned manifest capturing:
  - git commit hash + dirty status
  - core runtime environment versions
  - dataset locations / DOIs used in the paper
  - the exact commands used to regenerate each figure/table artifact

Outputs (tracked):
  - repro_manifest.json
  - appendix_repro_manifest.tex

Usage:
  PYTHONPATH=. python scripts/generate_repro_manifest.py
"""

from __future__ import annotations

import argparse
import json
import os
import platform
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable


REPO = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class DatasetInfo:
    name: str
    purpose: str
    local_path: str
    doi_or_url: str


@dataclass(frozen=True)
class ArtifactInfo:
    name: str
    paper_refs: list[str]
    outputs: list[str]
    commands: list[str]
    notes: str | None = None


def _run(cmd: list[str]) -> str:
    p = subprocess.run(cmd, cwd=str(REPO), check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    return p.stdout.strip()


def _git_info() -> dict[str, Any]:
    try:
        commit = _run(["git", "rev-parse", "HEAD"])
        short = _run(["git", "rev-parse", "--short", "HEAD"])
        branch = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
        status = _run(["git", "status", "--porcelain=v1"])
    except Exception as exc:
        return {"error": str(exc)}

    dirty_lines = [ln for ln in status.splitlines() if ln.strip()]
    return {
        "commit": commit,
        "commit_short": short,
        "branch": branch,
        "dirty": bool(dirty_lines),
        "dirty_paths": [ln.strip() for ln in dirty_lines[:200]],
    }


def _env_info() -> dict[str, Any]:
    versions: dict[str, str | None] = {}
    for pkg, mod_name in (
        ("numpy", "numpy"),
        ("scipy", "scipy"),
        ("torch", "torch"),
        ("matplotlib", "matplotlib"),
    ):
        try:
            mod = __import__(mod_name)
            versions[pkg] = getattr(mod, "__version__", None)
        except Exception:
            versions[pkg] = None

    return {
        "python": sys.version.splitlines()[0],
        "platform": platform.platform(),
        "machine": platform.machine(),
        "processor": platform.processor(),
        "versions": versions,
        "cwd": str(REPO),
    }


def _tex_escape(s: str) -> str:
    # Keep this minimal; we mostly use \path / verbatim for commands.
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
    )


def _render_verbatim_block(lines: Iterable[str]) -> str:
    body = "\n".join(lines).rstrip() + "\n"
    return "\\begin{verbatim}\n" + body + "\\end{verbatim}\n"


def _render_appendix_tex(manifest: dict[str, Any], *, out_path: Path) -> None:
    git = manifest.get("git") or {}
    env = manifest.get("env") or {}
    datasets = manifest.get("datasets") or []
    selections = manifest.get("selections") or {}
    artifacts = manifest.get("artifacts") or []

    def _sentence(s: str) -> str:
        s = str(s or "").strip()
        if not s:
            return ""
        return s if s.endswith(".") else s + "."

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/generate_repro_manifest.py; DO NOT EDIT BY HAND.")
    lines.append("\\section{Reproducibility Manifest}")
    lines.append("\\label{app:repro}")
    lines.append("")
    lines.append(
        "This appendix records a minimal reproduction recipe: exact commands, data locations, and a pinned repository state."
    )
    lines.append(
        "The manifest lists the minimal set of commands/outputs needed to reproduce the main claims; additional exploratory reports referenced in the text are not required unless explicitly listed here."
    )
    lines.append("Run \\path{PYTHONPATH=. python scripts/generate_repro_manifest.py} to refresh this manifest.")
    lines.append("")

    lines.append("\\paragraph{Repository state.}")
    if "error" in git:
        lines.append(f"Git metadata unavailable: {_tex_escape(str(git.get('error')))}.")
    else:
        lines.append(
            "Commit: "
            f"\\texttt{{{_tex_escape(str(git.get('commit_short') or ''))}}} "
            f"(full: \\texttt{{{_tex_escape(str(git.get('commit') or ''))}}}); "
            f"branch: \\texttt{{{_tex_escape(str(git.get('branch') or ''))}}}; "
            f"dirty: \\texttt{{{str(bool(git.get('dirty'))).lower()}}}."
        )
    lines.append("")

    lines.append("\\paragraph{Environment.}")
    versions = (env.get("versions") or {}) if isinstance(env, dict) else {}
    lines.append(f"Python: \\texttt{{{_tex_escape(str(env.get('python') or ''))}}}.")
    lines.append(f"Platform: \\texttt{{{_tex_escape(str(env.get('platform') or ''))}}}.")
    lines.append(
        "Packages: "
        + ", ".join(
            f"\\texttt{{{_tex_escape(k)}}}={{{_tex_escape(str(v))}}}"
            for k, v in versions.items()
            if v is not None
        )
        + "."
    )
    lines.append("")

    lines.append("\\paragraph{Datasets.}")
    lines.append(
        "Paths below are the expected on-disk locations used by the scripts in this repository. "
        "Large outputs under \\path{runs/} and \\path{reports/} are not tracked."
    )
    lines.append("\\begin{itemize}[nosep]")
    for ds in datasets:
        if not isinstance(ds, dict):
            continue
        lines.append(
            "  \\item "
            f"\\textbf{{{_tex_escape(str(ds.get('name') or ''))}}}: "
            f"{_tex_escape(str(ds.get('purpose') or ''))} "
            f"(local: \\path{{{str(ds.get('local_path') or '')}}}; "
            f"source: \\path{{{str(ds.get('doi_or_url') or '')}}})."
        )
    lines.append("\\end{itemize}")
    lines.append("")

    lines.append("\\paragraph{Pre-registered selections used in this manuscript.}")
    lines.append("\\begin{itemize}[nosep]")
    for k, v in selections.items():
        lines.append(f"  \\item \\textbf{{{_tex_escape(str(k))}}}: {_tex_escape(_sentence(str(v)))}")
    lines.append("\\end{itemize}")
    lines.append("")

    lines.append("\\paragraph{Artifact commands.}")
    lines.append(
        "Each entry below lists the command(s) used to regenerate the referenced paper artifact(s). "
        "Most scripts write a JSON summary containing the full parameterization and are safe to rerun."
    )
    lines.append("\\begin{enumerate}[label=(R\\arabic*),nosep]")
    for art in artifacts:
        if not isinstance(art, dict):
            continue
        name = str(art.get("name") or "")
        refs = art.get("paper_refs") or []
        outs = art.get("outputs") or []
        cmds = art.get("commands") or []
        notes = art.get("notes")

        lines.append(f"  \\item \\textbf{{{_tex_escape(name)}}}")
        if refs:
            ref_text = ", ".join(_tex_escape(str(r)) for r in refs)
            lines.append(f"    (paper refs: {ref_text}).")
        else:
            lines.append(".")
        if outs:
            lines.append("    Outputs: " + ", ".join(f"\\path{{{str(o)}}}" for o in outs) + ".")
        if notes:
            lines.append("    Notes: " + _tex_escape(_sentence(str(notes))))
        if cmds:
            lines.append(_render_verbatim_block([str(c) for c in cmds]))
    lines.append("\\end{enumerate}")
    lines.append("")

    out_path.write_text("\n".join(lines) + "\n")


def _default_datasets() -> list[DatasetInfo]:
    return [
        DatasetInfo(
            name="Brain-* k-Wave pilots (simulated IQ)",
            purpose="Labeled low-FPR ROC + ablations.",
            local_path="runs/pilot/",
            doi_or_url="(generated locally via sim/kwave/pilot_motion.py / Makefile targets r4c-*)",
        ),
        DatasetInfo(
            name="Mace/Urban whole-brain mouse fUS (PD-only)",
            purpose="PD-only telemetry + hold-out alias-gate evaluation (no Doppler IQ).",
            local_path="data/whole-brain-fUS",
            doi_or_url="https://doi.org/10.5281/zenodo.4905862",
        ),
        DatasetInfo(
            name="Shin RatBrain Fig3 (LOCA-ULM) beamformed IQ",
            purpose="Real-IQ ingestion/telemetry/contract + label-free robustness sweeps.",
            local_path="data/shin_zenodo_10711806/RatBrain_Fig3.zip (extracts to data/shin_zenodo_10711806/ratbrain_fig3_raw)",
            doi_or_url="https://doi.org/10.5281/zenodo.10711806",
        ),
    ]


def _default_selections() -> dict[str, str]:
    return {
        "Brain seed sweep (AliasContract pilot)": "seed2-seed12 (n=11).",
        "Shin all-clips telemetry": "IQData001-IQData080 (n=80), window 0:128.",
        "Shin motion subset": "IQData001-005, IQData010, IQData020, IQData040, IQData060, IQData080 (n=10).",
        "Mace holdout split (deduplicated)": "train: scan1/2 + scan3/6; test: scan4 + scan5.",
    }


def _default_artifacts() -> list[ArtifactInfo]:
    return [
        ArtifactInfo(
            name="PD-mode sanity checks (PD-mode map and score S=-PD)",
            paper_refs=["Notation (PD convention)"],
            outputs=["reports/pd_mode_sanity/ (optional figs)"],
            commands=[
                "PYTHONPATH=. python scripts/pd_mode_sanity.py runs/<bundle_root>/pw_* --out-dir reports/pd_mode_sanity",
            ],
            notes="Run on any generated acceptance bundle root containing pw_* directories.",
        ),
        ArtifactInfo(
            name="Conditional STAP leakage ablation (full vs conditional masks)",
            paper_refs=["Results (Brain-k-Wave): conditional STAP ablation"],
            outputs=["reports/condstap_leakage.csv", "reports/condstap_leakage.json"],
            commands=[
                "PYTHONPATH=. python scripts/conditional_stap_leakage_ablation.py \\",
                "  --pilots runs/pilot/r4_kwave_seed1 runs/pilot/r4_kwave_seed2 \\",
                "  --profile Brain-OpenSkull \\",
                "  --out-root runs/ablation/condstap_leakage \\",
                "  --window-length 64 --window-offset 0 --disjoint-offset 64 \\",
                "  --summary-csv reports/condstap_leakage.csv \\",
                "  --summary-json reports/condstap_leakage.json",
            ],
        ),
        ArtifactInfo(
            name="Brain-* baseline fairness: MC--SVD(e) tune-once sweep",
            paper_refs=["Baseline fairness (Brain-*)"],
            outputs=["reports/brain_mcsvd_energy_sweep.csv", "reports/brain_mcsvd_energy_sweep.json"],
            commands=[
                "PYTHONPATH=. python scripts/brain_mcsvd_energy_sweep.py \\",
                "  --pilot runs/pilot/r4_kwave_seed1 \\",
                "  --profile Brain-OpenSkull \\",
                "  --out-root runs/sweep/mcsvd_energy_brain_seed1 \\",
                "  --window-length 64 --window-offset 0 \\",
                "  --energy-fracs 0.90,0.95,0.97,0.975,0.98,0.99 \\",
                "  --fprs 1e-4,3e-4,1e-3 \\",
                "  --summary-csv reports/brain_mcsvd_energy_sweep.csv \\",
                "  --summary-json reports/brain_mcsvd_energy_sweep.json",
            ],
        ),
        ArtifactInfo(
            name="KA Contract v2 falsifiability ablation (STAP-only vs contract vs forced)",
            paper_refs=["KA evaluation discipline"],
            outputs=["reports/ka_v2_ablation.csv", "reports/ka_v2_ablation.json"],
            commands=[
                "PYTHONPATH=. python scripts/ka_contract_v2_ablation.py \\",
                "  --pilot runs/pilot/r4c_kwave_hab_contract_seed2 \\",
                "  --profile Brain-AliasContract \\",
                "  --out-root runs/ablation/ka_v2_falsifiability \\",
                "  --stap-device cpu \\",
                "  --window-length 64 \\",
                "  --window-offsets 0 64 128 192 256 \\",
                "  --summary-csv reports/ka_v2_ablation.csv \\",
                "  --summary-json reports/ka_v2_ablation.json",
            ],
        ),
        ArtifactInfo(
            name="Mace PD-only holdout alias-gate evaluation (label-free thresholds)",
            paper_refs=["Table: Mace hold-out alias gate"],
            outputs=["reports/mace_alias_gate_holdout.csv", "reports/mace_alias_gate_holdout.json"],
            commands=[
                "PYTHONPATH=. python scripts/mace_alias_gate_holdout.py \\",
                "  --out-csv reports/mace_alias_gate_holdout.csv \\",
                "  --out-json reports/mace_alias_gate_holdout.json",
            ],
        ),
        ArtifactInfo(
            name="Mace pixel-level vascular-atlas check (independent structural labels)",
            paper_refs=["Macé section: vascular atlas pixel-level check"],
            outputs=["reports/mace_vascular_pixel_eval.csv", "reports/mace_vascular_pixel_eval.json"],
            commands=[
                "PYTHONPATH=. python scripts/mace_vascular_pixel_eval.py \\",
                "  --out-csv reports/mace_vascular_pixel_eval.csv \\",
                "  --out-json reports/mace_vascular_pixel_eval.json",
            ],
            notes="Maps atlas.Vascular into each scan plane using Transformation.mat; evaluates vascular vs non-vascular pixels (structural, not clinical efficacy).",
        ),
        ArtifactInfo(
            name="Mace atlas-alignment sanity overlay figure",
            paper_refs=["Appendix: Macé atlas alignment sanity check"],
            outputs=["figs/paper/mace_atlas_overlay.png"],
            commands=[
                "PYTHONPATH=. python scripts/mace_atlas_overlay_fig.py \\",
                "  --scan-name scan1 \\",
                "  --plane-indices 5 10 15 \\",
                "  --out-png figs/paper/mace_atlas_overlay.png",
            ],
            notes="Overlays atlas ROIs and atlas.Vascular contours on mean PD for representative planes (sanity check of Transformation.mat alignment).",
        ),
        ArtifactInfo(
            name="Mace PD-only contract v2 dashboard (plane sweep + paper figure)",
            paper_refs=["Figure: mace_pdonly_contract_v2_dashboard.png"],
            outputs=["reports/mace_pdonly_contract_v2.csv", "figs/paper/mace_pdonly_contract_v2_dashboard.png"],
            commands=[
                "PYTHONPATH=. python scripts/mace_pdonly_contract_v2_sweep.py \\",
                "  --out-csv reports/mace_pdonly_contract_v2.csv",
                "",
                "PYTHONPATH=. python scripts/mace_pdonly_contract_v2_dashboard_fig.py \\",
                "  --in-csv reports/mace_pdonly_contract_v2.csv \\",
                "  --out-png figs/paper/mace_pdonly_contract_v2_dashboard.png",
            ],
        ),
        ArtifactInfo(
            name="Shin all-clips contract telemetry (n=80; telemetry-only)",
            paper_refs=["Shin section: all-clips telemetry audit"],
            outputs=[
                "reports/shin_ratbrain_shinU_e970_telemetry_only_0_128_all80.csv",
                "reports/shin_ratbrain_shinU_e970_telemetry_only_0_128_all80_summary.json",
            ],
            commands=[
                "PYTHONPATH=. python -m scripts.shin_ratbrain_allclips_contract_hygiene \\",
                "  --extract-from-zip --no-run-stap --no-score-ka-v2 \\",
                "  --profile U --svd-energy-frac 0.97 --frames-list 0:128 \\",
                "  --out-root runs/shin_ratbrain_shinU_e970_telemetry_only_0_128_all80 \\",
                "  --out-csv reports/shin_ratbrain_shinU_e970_telemetry_only_0_128_all80.csv \\",
                "  --out-json reports/shin_ratbrain_shinU_e970_telemetry_only_0_128_all80_summary.json",
            ],
        ),
        ArtifactInfo(
            name="Shin brainlike motion sweep (10 clips) + aggregate plots",
            paper_refs=[
                "Table: Shin motion endpoints",
                "Figure: shin_motion_brainlike_batch_U_agg.png",
                "Figure: shin_motion_brainlike_compare_reg1.png",
                "Figure: shin_motion_brainlike_compare.png",
            ],
            outputs=[
                "reports/shin_motion_brainlike_batch_U/*.csv",
                "reports/shin_motion_brainlike_batch_U_agg.csv",
                "figs/paper/shin_motion_brainlike_batch_U_agg.png",
                "figs/paper/shin_motion_brainlike_compare_reg1.png",
                "figs/paper/shin_motion_brainlike_compare.png",
            ],
            commands=[
                "# Per-clip sweeps (canonical window 0:128; KA disabled):",
                "for f in IQData001.dat IQData002.dat IQData003.dat IQData004.dat IQData005.dat IQData010.dat IQData020.dat IQData040.dat IQData060.dat IQData080.dat; do",
                "  PYTHONPATH=. python -m scripts.shin_ratbrain_motion_sweep \\",
                "    --iq-file \"$f\" --frames 0:128 --profile U --svd-energy-frac 0.97 \\",
                "    --motion-kind brainlike --amp-px-list 0,0.5,1,2 \\",
                "    --no-score-ka-v2 --out-root runs/shin_motion_brainlike_batch_U \\",
                "    --out-csv \"reports/shin_motion_brainlike_batch_U/${f%.dat}.csv\" \\",
                "    --out-png \"reports/shin_motion_brainlike_batch_U/${f%.dat}.png\";",
                "done",
                "",
                "# Aggregate curve (writes CSV + plot):",
                "PYTHONPATH=. python -m scripts.shin_ratbrain_motion_aggregate \\",
                "  --in-dir reports/shin_motion_brainlike_batch_U \\",
                "  --out-csv reports/shin_motion_brainlike_batch_U_agg.csv \\",
                "  --out-png reports/shin_motion_brainlike_batch_U_agg.png",
                "",
                "# Compare across windows / reg ablations (writes comparison plots):",
                "PYTHONPATH=. python -m scripts.shin_ratbrain_motion_compare \\",
                "  --curve \"0:128=reports/shin_motion_brainlike_batch_U_agg.csv\" \\",
                "  --curve \"64:192=reports/shin_motion_brainlike_batch_U_f64_192_reg1_agg.csv\" \\",
                "  --curve \"122:250=reports/shin_motion_brainlike_batch_U_f122_250_reg1_agg.csv\" \\",
                "  --out-png reports/shin_motion_brainlike_compare_reg1.png",
                "cp -f reports/shin_motion_brainlike_compare_reg1.png figs/paper/shin_motion_brainlike_compare_reg1.png",
            ],
            notes="Window-specific batch runs (64:192, 122:250) follow the same pattern; see scripts/shin_ratbrain_motion_aggregate.py for expected inputs.",
        ),
        ArtifactInfo(
            name="Shin motion crop/alignment sensitivity (post-hoc)",
            paper_refs=["Shin motion section: crop sensitivity note"],
            outputs=["reports/shin_motion_brainlike_batch_U_crop_sensitivity.csv"],
            commands=[
                "PYTHONPATH=. python -m scripts.shin_ratbrain_motion_sensitivity_posthoc \\",
                "  --run-root runs/shin_motion_brainlike_batch_U \\",
                "  --amps 0,0.5,1,2 \\",
                "  --crop-margins 0,4,8,12 \\",
                "  --align-maps-list 0,1 \\",
                "  --out-csv reports/shin_motion_brainlike_batch_U_crop_sensitivity.csv",
            ],
        ),
        ArtifactInfo(
            name="Paper build modes (paper vs supplement vs full)",
            paper_refs=["Build packaging (Phase 7)"],
            outputs=["stap_fus_paper.pdf", "stap_fus_supplement.pdf", "stap_fus_methodology.pdf"],
            commands=[
                "pdflatex stap_fus_methodology.tex   # full (default)",
                "pdflatex stap_fus_paper.tex         # paper-only (no appendices)",
                "pdflatex stap_fus_supplement.tex    # supplement-only (appendices only)",
            ],
        ),
    ]


def build_manifest() -> dict[str, Any]:
    manifest: dict[str, Any] = {
        "git": _git_info(),
        "env": _env_info(),
        "datasets": [asdict(d) for d in _default_datasets()],
        "selections": _default_selections(),
        "artifacts": [asdict(a) for a in _default_artifacts()],
    }
    return manifest


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate reproducibility manifest (JSON + LaTeX appendix).")
    ap.add_argument("--out-json", type=Path, default=Path("repro_manifest.json"))
    ap.add_argument("--out-tex", type=Path, default=Path("appendix_repro_manifest.tex"))
    return ap.parse_args()


def main() -> None:
    args = parse_args()

    manifest = build_manifest()
    args.out_json.write_text(json.dumps(manifest, indent=2))
    _render_appendix_tex(manifest, out_path=args.out_tex)

    print(f"[repro-manifest] wrote {args.out_json}")
    print(f"[repro-manifest] wrote {args.out_tex}")


if __name__ == "__main__":
    main()
