#!/usr/bin/env python3
"""
Run a frozen latency preset and emit a compact paper-facing summary table.

This is intentionally narrow: it codifies the currently supported 4080 product
preset so that latency reruns come from one named entry point instead of a pile
of ad hoc shell flags.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


REPO = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class ScenarioRow:
    scenario: str
    baseline_s: float
    detector_s: float
    total_s: float
    budget_s: float

    @property
    def rtf(self) -> float:
        return float(self.total_s / self.budget_s)


def _load_telemetry(meta_path: Path) -> dict[str, Any]:
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    tele = meta.get("stap_fallback_telemetry") or {}
    return tele if isinstance(tele, dict) else {}


def _mean(values: list[float]) -> float:
    if not values:
        raise ValueError("Cannot take mean of empty list.")
    return float(sum(values) / float(len(values)))


def _brain_summary(out_root: Path, profile: str, budget_s: float) -> ScenarioRow:
    metas = sorted((out_root / "optimized").glob("pw_*/meta.json"))
    if len(metas) < 2:
        raise RuntimeError(f"{profile}: expected >=2 optimized brain bundles under {out_root / 'optimized'}")
    teles = [_load_telemetry(p) for p in metas]
    baseline_s = _mean([float(t.get("baseline_ms", 0.0)) / 1000.0 for t in teles[1:]])
    detector_s = _mean([float(t.get("stap_total_ms", 0.0)) / 1000.0 for t in teles[1:]])
    return ScenarioRow(
        scenario={
            "Brain-OpenSkull": "Open-skull surface-artifact stress test (64-frame window)",
            "Brain-AliasContract": "Alias-dominant positive control (64-frame window)",
            "Brain-SkullOR": "Structured-clutter leakage stress test (64-frame window)",
        }.get(profile, profile),
        baseline_s=baseline_s,
        detector_s=detector_s,
        total_s=baseline_s + detector_s,
        budget_s=budget_s,
    )


def _shin_summary(out_root: Path, budget_s: float) -> ScenarioRow:
    metas = sorted((out_root / "shin" / "stap_conditional").rglob("meta.json"))
    if len(metas) < 2:
        raise RuntimeError(f"Shin: expected >=2 conditional bundles under {out_root / 'shin' / 'stap_conditional'}")
    teles = [_load_telemetry(p) for p in metas]
    baseline_s = _mean([float(t.get("baseline_ms", 0.0)) / 1000.0 for t in teles[1:]])
    detector_s = _mean([float(t.get("stap_total_ms", 0.0)) / 1000.0 for t in teles[1:]])
    return ScenarioRow(
        scenario="Shin rat-brain real-IQ audit (128-frame window)",
        baseline_s=baseline_s,
        detector_s=detector_s,
        total_s=baseline_s + detector_s,
        budget_s=budget_s,
    )


def _gammex_view_summary(out_root: Path, view_prefix: str, label: str, budget_s: float) -> ScenarioRow:
    roots = sorted((out_root / "gammex").glob(f"{view_prefix}*/stap_full/*"))
    if len(roots) != 1:
        raise RuntimeError(
            f"{label}: expected exactly one bundle root under {(out_root / 'gammex')} matching {view_prefix}*"
        )
    metas = sorted(roots[0].glob("frame*/meta.json"))
    if len(metas) < 2:
        raise RuntimeError(f"{label}: expected >=2 frame bundles under {roots[0]}")
    teles = [_load_telemetry(p) for p in metas]
    baseline_s = _mean([float(t.get("baseline_ms", 0.0)) / 1000.0 for t in teles[1:]])
    detector_s = _mean([float(t.get("stap_total_ms", 0.0)) / 1000.0 for t in teles[1:]])
    return ScenarioRow(
        scenario=label,
        baseline_s=baseline_s,
        detector_s=detector_s,
        total_s=baseline_s + detector_s,
        budget_s=budget_s,
    )


def _run_command(cmd: list[str], *, env: dict[str, str], cwd: Path) -> None:
    proc = subprocess.run(cmd, cwd=str(cwd), env=env, text=True)
    if proc.returncode != 0:
        raise SystemExit(proc.returncode)


def _format_s(v: float) -> str:
    return f"{v:.3f}"


def _render_tex(out_tex: Path, rows: list[ScenarioRow], *, preset_name: str) -> None:
    lines = [
        "% AUTO-GENERATED by scripts/run_latency_named_preset.py; DO NOT EDIT BY HAND.",
        "\\begin{table}[ht]",
        "\\centering",
        "\\small",
        "\\resizebox{\\linewidth}{!}{%",
        "\\begin{tabular}{P{6.0cm} c c c c c}",
        "\\hline",
        "Scenario & Baseline (s) & Detector (s) & Total (s) & Budget (s) & RTF \\\\",
        "\\hline",
    ]
    for row in rows:
        lines.append(
            f"{row.scenario} & ${_format_s(row.baseline_s)}$ & ${_format_s(row.detector_s)}$ "
            f"& ${_format_s(row.total_s)}$ & ${_format_s(row.budget_s)}$ & ${row.rtf:.2f}$ \\\\"
        )
    lines.extend(
        [
            "\\hline",
            "\\end{tabular}%",
            "}",
            (
                f"\\caption{{Steady-state latency summary for preset \\texttt{{{preset_name}}} on an "
                "NVIDIA GeForce RTX 4080 SUPER 16GB. Times are means over windows/frames 2..N, "
                "exclude disk I/O, and time the frozen product-path detector hierarchy rather than "
                "the older specialist-path timing configuration.}}"
            ),
            "\\label{tab:latency_summary_4080super_product}",
            "\\end{table}",
        ]
    )
    out_tex.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--preset",
        type=str,
        default="rtx4080_prf_product_v1",
        choices=["rtx4080_prf_product_v1"],
        help="Named latency preset to run.",
    )
    ap.add_argument(
        "--out-root",
        type=Path,
        default=Path("runs/latency_named_preset/rtx4080_prf_product_v1"),
        help="Output root for all replay artifacts.",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=Path("reports/latency_named_preset_rtx4080_prf_product_v1.json"),
        help="Summary JSON output.",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/latency_named_preset_rtx4080_prf_product_v1_table.tex"),
        help="Paper-facing LaTeX table output.",
    )
    ap.add_argument(
        "--brain-src",
        type=Path,
        default=Path("runs/pilot/r4c_kwave_seed1"),
        help="Source pilot root for the brain replay latency harness.",
    )
    ap.add_argument(
        "--clean",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Delete any existing out-root before rerunning (default: %(default)s).",
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    out_root = args.out_root.resolve()
    if args.clean and out_root.exists():
        shutil.rmtree(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)

    env = dict(os.environ)
    env["PYTHONPATH"] = str(REPO)

    # Brain product path: static-window brain replay with the shipped simple
    # head, exact zero-motion bypass, and a fixed conditional tile threshold.
    brain_env = dict(env)
    brain_env["STAP_CONDITIONAL_TILE_MIN_FRAC"] = "0.40"
    brain_rows: list[ScenarioRow] = []
    for profile in ("Brain-OpenSkull", "Brain-AliasContract", "Brain-SkullOR"):
        profile_slug = profile.lower().replace("-", "_")
        profile_out = out_root / "brain" / profile_slug
        cmd = [
            sys.executable,
            "scripts/latency_rerun_check.py",
            "--src",
            str(args.brain_src),
            "--out-root",
            str(profile_out),
            "--profile",
            profile,
            "--baseline",
            "mc_svd",
            "--baseline-support",
            "window",
            "--stap-device",
            "cuda",
            "--stap-detector-variant",
            "unwhitened_ratio",
            "--stap-conditional",
            "on",
            "--window-offsets",
            "0,64,128,192,256",
            "--tile-batch",
            "512",
            "--replay-extra=--reg-disable",
        ]
        _run_command(cmd, env=brain_env, cwd=REPO)
        brain_rows.append(_brain_summary(profile_out, profile, budget_s=(64.0 / 1500.0)))

    # Shin product path: frozen low-frequency adaptive product used in the real-IQ audit.
    shin_out = out_root / "shin"
    shin_cmd = [
        sys.executable,
        "scripts/latency_realdata_rerun_check.py",
        "--out-root",
        str(shin_out),
        "--stap-device",
        "cuda",
        "--stap-detector-variant",
        "adaptive_guard",
        "--tile-batch",
        "192",
        "shin",
        "--flow-low-hz",
        "20",
        "--flow-high-hz",
        "200",
        "--alias-center-hz",
        "380",
        "--alias-width-hz",
        "120",
        "--Lt",
        "64",
    ]
    _run_command(shin_cmd, env=env, cwd=REPO)
    shin_row = _shin_summary(shin_out, budget_s=(128.0 / 1000.0))

    # Gammex product path: true raw baseline + simple fixed head with coarser
    # frozen geometry per view to make the short-ensemble phantom path streamable.
    gammex_out = out_root / "gammex"
    gammex_cmd = [
        sys.executable,
        "scripts/latency_realdata_rerun_check.py",
        "--out-root",
        str(gammex_out),
        "--stap-device",
        "cuda",
        "--stap-detector-variant",
        "unwhitened_ratio",
        "--tile-batch",
        "1024",
        "gammex",
        "--baseline-type",
        "raw",
        "--along-tile-stride",
        "24",
        "--across-tile-stride",
        "6",
    ]
    _run_command(gammex_cmd, env=env, cwd=REPO)
    gammex_along = _gammex_view_summary(
        gammex_out,
        "along_linear17",
        "Gammex flow phantom, along view (17-shot cine frame)",
        budget_s=(17.0 / 2500.0),
    )
    gammex_across = _gammex_view_summary(
        gammex_out,
        "across_linear17",
        "Gammex flow phantom, across view (17-shot cine frame)",
        budget_s=(17.0 / 2500.0),
    )

    rows = brain_rows + [shin_row, gammex_along, gammex_across]
    payload = {
        "preset": args.preset,
        "rows": [
            {
                "scenario": row.scenario,
                "baseline_s": row.baseline_s,
                "detector_s": row.detector_s,
                "total_s": row.total_s,
                "budget_s": row.budget_s,
                "rtf": row.rtf,
            }
            for row in rows
        ],
    }
    args.out_json.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    _render_tex(args.out_tex, rows, preset_name=args.preset)
    print(json.dumps(payload, indent=2))


if __name__ == "__main__":
    main()
