#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np


ROOT = Path(__file__).resolve().parents[1]


def _finite(x: np.ndarray) -> np.ndarray:
    arr = np.asarray(x, dtype=np.float64).ravel()
    return arr[np.isfinite(arr)]


def _threshold_from_neg(neg: np.ndarray, fpr: float) -> tuple[float | None, float | None]:
    neg_f = _finite(neg)
    if neg_f.size == 0:
        return None, None
    q = float(np.clip(1.0 - float(fpr), 0.0, 1.0))
    thr = float(np.quantile(neg_f, q))
    fpr_emp = float(np.mean(neg_f >= thr))
    return thr, fpr_emp


def _bootstrap_ci(
    xs: list[float | None],
    *,
    n_boot: int = 2000,
    seed: int = 0,
) -> dict[str, float | int | None]:
    arr = np.asarray([x for x in xs if x is not None and np.isfinite(x)], dtype=np.float64)
    if arr.size == 0:
        return {"center": None, "lo": None, "hi": None, "n": 0}
    center = float(np.mean(arr))
    rng = np.random.default_rng(seed)
    idx = rng.integers(0, arr.size, size=(n_boot, arr.size))
    boots = np.mean(arr[idx], axis=1)
    lo, hi = np.quantile(boots, [0.025, 0.975])
    return {"center": center, "lo": float(lo), "hi": float(hi), "n": int(arr.size)}


def _fmt(x: float | None, digits: int = 3) -> str:
    if x is None or not np.isfinite(float(x)):
        return "--"
    return f"{float(x):.{digits}f}"


def _alpha_tex(alpha: float) -> str:
    exponent = int(round(np.log10(float(alpha))))
    return rf"10^{{{exponent}}}"


def _score_label(score_key: str) -> str:
    return {
        "pd": "Baseline (power Doppler)",
        "kasai": "Baseline (Kasai lag-1 magnitude)",
        "matched_subspace": "Fixed matched-subspace detector",
    }[score_key]


def _iter_scenarios(root: Path) -> list[dict[str, Any]]:
    patt = re.compile(
        r"^shin_(IQData(?P<clip>\d+))_f(?P<start>\d+)_(?P<stop>\d+)_pU_Lt64_mcsvd_e0p970_stap$"
    )
    out: list[dict[str, Any]] = []
    for meta_path in root.rglob("meta.json"):
        bundle_dir = meta_path.parent
        m = patt.match(bundle_dir.name)
        if not m:
            continue
        required = [
            bundle_dir / "mask_flow.npy",
            bundle_dir / "mask_bg.npy",
            bundle_dir / "score_base.npy",
            bundle_dir / "score_base_kasai.npy",
            bundle_dir / "score_stap_preka.npy",
        ]
        if not all(p.is_file() for p in required):
            continue
        out.append(
            {
                "clip_name": str(m.group(1)),
                "clip_id": int(m.group("clip")),
                "window_start": int(m.group("start")),
                "window_stop": int(m.group("stop")),
                "bundle_dir": bundle_dir,
            }
        )
    out.sort(key=lambda rec: (int(rec["clip_id"]), int(rec["window_start"]), int(rec["window_stop"])))
    return out


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _build_table(summary_rows: list[dict[str, Any]], *, alpha: float) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/shin_fixed_calibration_transfer.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\begin{tabular}{lcc}")
    lines.append("\\hline")
    lines.append("Score & flow-proxy hit rate & realized bg-proxy FPR \\\\")
    lines.append("\\hline")
    for key in ("pd", "kasai", "matched_subspace"):
        sec = next(r for r in summary_rows if r["score_key"] == key)
        lines.append(
            f"{sec['score_label']} & "
            f"{_fmt(sec['heldout_hit_flow_proxy']['center'])} [{_fmt(sec['heldout_hit_flow_proxy']['lo'])},{_fmt(sec['heldout_hit_flow_proxy']['hi'])}] & "
            f"{_fmt(sec['heldout_fpr_bg_proxy']['center'])} [{_fmt(sec['heldout_fpr_bg_proxy']['lo'])},{_fmt(sec['heldout_fpr_bg_proxy']['hi'])}] \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Fixed-calibration transfer on the Shin rat-brain real-IQ proxy audit at "
        f"nominal $\\alpha={_alpha_tex(alpha)}$. A threshold is learned once from pooled background-proxy negatives on one 5-clip calibration bank and then applied unchanged to the complementary 5 held-out clips across all three audited windows per clip. Reported values pool the two complementary clip splits and show scenario-level means with 95\\% bootstrap CIs. Because Shin does not provide independent task labels, this is a secondary proxy-based deployment check rather than a task ROC result.}}"
    )
    lines.append("\\label{tab:shin_fixed_calibration_transfer}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def run(args: argparse.Namespace) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    scenarios = _iter_scenarios(Path(args.run_root))
    if not scenarios:
        raise FileNotFoundError(f"No Shin baseline-matrix bundles found under {args.run_root}")
    clip_ids = sorted({int(rec["clip_id"]) for rec in scenarios})
    if len(clip_ids) != 10:
        print(f"[shin-fixed-cal] warning: expected 10 clips, found {len(clip_ids)}")
    mid = len(clip_ids) // 2
    split_defs = [
        {"split": "clips_firsthalf_to_secondhalf", "train": clip_ids[:mid], "eval": clip_ids[mid:]},
        {"split": "clips_secondhalf_to_firsthalf", "train": clip_ids[mid:], "eval": clip_ids[:mid]},
    ]
    score_files = {
        "pd": "score_base.npy",
        "kasai": "score_base_kasai.npy",
        "matched_subspace": "score_stap_preka.npy",
    }
    rows: list[dict[str, Any]] = []
    for split in split_defs:
        train_negs: dict[str, list[np.ndarray]] = defaultdict(list)
        eval_cache: list[dict[str, Any]] = []
        for rec in scenarios:
            bundle_dir = Path(rec["bundle_dir"])
            mask_flow = np.load(bundle_dir / "mask_flow.npy", allow_pickle=False).astype(bool)
            mask_bg = np.load(bundle_dir / "mask_bg.npy", allow_pickle=False).astype(bool)
            scores = {
                key: np.load(bundle_dir / fname, allow_pickle=False).astype(np.float32, copy=False)
                for key, fname in score_files.items()
            }
            if int(rec["clip_id"]) in split["train"]:
                for score_key, score in scores.items():
                    train_negs[score_key].append(score[mask_bg])
            if int(rec["clip_id"]) in split["eval"]:
                eval_cache.append({**rec, "mask_flow": mask_flow, "mask_bg": mask_bg, "scores": scores})

        thresholds: dict[str, tuple[float, float]] = {}
        for score_key in ("pd", "kasai", "matched_subspace"):
            thr, realized = _threshold_from_neg(
                _finite(np.concatenate(train_negs[score_key], axis=0)),
                float(args.alpha),
            )
            if thr is None:
                raise RuntimeError(f"failed to calibrate {score_key} on split {split['split']}")
            thresholds[score_key] = (float(thr), float(realized))

        for rec in eval_cache:
            for score_key, score in rec["scores"].items():
                thr, calib_fpr = thresholds[score_key]
                pos = _finite(score[rec["mask_flow"]])
                neg = _finite(score[rec["mask_bg"]])
                rows.append(
                    {
                        "split": str(split["split"]),
                        "clip_name": str(rec["clip_name"]),
                        "clip_id": int(rec["clip_id"]),
                        "window_start": int(rec["window_start"]),
                        "window_stop": int(rec["window_stop"]),
                        "score_key": str(score_key),
                        "score_label": _score_label(str(score_key)),
                        "alpha_nominal": float(args.alpha),
                        "threshold": float(thr),
                        "calibration_bg_proxy_fpr": float(calib_fpr),
                        "heldout_hit_flow_proxy": float(np.mean(pos >= thr)) if pos.size else None,
                        "heldout_fpr_bg_proxy": float(np.mean(neg >= thr)) if neg.size else None,
                        "n_flow_proxy": int(pos.size),
                        "n_bg_proxy": int(neg.size),
                    }
                )

    summary_rows: list[dict[str, Any]] = []
    for score_key in ("pd", "kasai", "matched_subspace"):
        subset = [r for r in rows if r["score_key"] == score_key]
        summary_rows.append(
            {
                "score_key": str(score_key),
                "score_label": _score_label(str(score_key)),
                "heldout_hit_flow_proxy": _bootstrap_ci(
                    [r["heldout_hit_flow_proxy"] for r in subset],
                    n_boot=int(args.bootstrap_n),
                    seed=int(args.bootstrap_seed) + 31,
                ),
                "heldout_fpr_bg_proxy": _bootstrap_ci(
                    [r["heldout_fpr_bg_proxy"] for r in subset],
                    n_boot=int(args.bootstrap_n),
                    seed=int(args.bootstrap_seed) + 47,
                ),
                "n_scenarios": int(len(subset)),
                "n_clips": int(len({int(r["clip_id"]) for r in subset})),
            }
        )
    return rows, summary_rows


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Fixed-calibration transfer on the Shin rat-brain proxy audit.")
    ap.add_argument(
        "--run-root",
        type=Path,
        default=ROOT / "runs" / "shin_ratbrain_baseline_matrix_shinU_e970_Lt64_nomaskunion_k80",
    )
    ap.add_argument("--alpha", type=float, default=1e-3)
    ap.add_argument("--bootstrap-n", type=int, default=2000)
    ap.add_argument("--bootstrap-seed", type=int, default=2468)
    ap.add_argument("--out-csv", type=Path, default=ROOT / "reports" / "shin_fixed_calibration_transfer.csv")
    ap.add_argument("--out-json", type=Path, default=ROOT / "reports" / "shin_fixed_calibration_transfer.json")
    ap.add_argument("--out-tex", type=Path, default=ROOT / "reports" / "shin_fixed_calibration_transfer_table.tex")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    rows, summary_rows = run(args)
    _write_csv(Path(args.out_csv), rows)
    Path(args.out_tex).write_text(_build_table(summary_rows, alpha=float(args.alpha)), encoding="utf-8")
    _write_json(
        Path(args.out_json),
        {"alpha_nominal": float(args.alpha), "shin": {"rows": rows, "summary": summary_rows}},
    )
    print(f"[shin-fixed-cal] wrote {args.out_json}")


if __name__ == "__main__":
    main()
