#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path


SETTING_ROWS = {
    "Mobile": {
        "seed_prefix": "mobile",
        "public": {
            "method_family": "hosvd",
            "config_name": "rank8_16_16_ds2_t32",
            "detector_head": "kasai",
            "label": r"HOSVD $\rightarrow$ Kasai",
        },
        "fixed": {
            "method_family": "svd_similarity",
            "config_name": "conservative_r8",
            "candidate": "unwhitened_ref",
            "label": r"Adaptive Global SVD $\rightarrow$ fixed matched-subspace",
        },
    },
    "Intra-operative parenchymal": {
        "seed_prefix": "intraop",
        "public": {
            "method_family": "hosvd",
            "config_name": "rank8_16_16_ds2_t32",
            "detector_head": "kasai",
            "label": r"HOSVD $\rightarrow$ Kasai",
        },
        "fixed": {
            "method_family": "rpca",
            "config_name": "lam1_it250_ds2_t32_r4",
            "candidate": "unwhitened_ref",
            "label": r"RPCA $\rightarrow$ fixed matched-subspace",
        },
    },
}


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _fmt(x: str | float) -> str:
    value = float(x)
    if 0.999 < value < 1.0:
        return f"{value:.5f}"
    return f"{value:.3f}"


def _fmt_fpr_with_zero_note(x: str | float) -> str:
    value = float(x)
    formatted = _fmt(value)
    if formatted == "0.000":
        return formatted + r"$^{\dagger}$"
    return formatted


def _fmt_summary(values: list[str | float], *, zero_note: bool = False) -> str:
    nums = [float(v) for v in values]
    mean = sum(nums) / len(nums)
    lo = min(nums)
    hi = max(nums)
    if zero_note and mean == 0.0 and lo == 0.0 and hi == 0.0:
        return f"{_fmt(mean)}$^{{\\dagger}}$ [{_fmt(lo)},{_fmt(hi)}]"
    return f"{_fmt(mean)} [{_fmt(lo)},{_fmt(hi)}]"


def _find_public_row(rows: list[dict[str, str]], *, setting: str, seed: str, spec: dict[str, str]) -> dict[str, str]:
    case_name = f"{SETTING_ROWS[setting]['seed_prefix']}{seed}"
    for row in rows:
        inferred_setting = "Mobile" if row["case_name"].startswith("mobile") else "Intra-operative parenchymal"
        if (
            row["split"] == "eval"
            and inferred_setting == setting
            and row["case_name"] == case_name
            and row["method_family"] == spec["method_family"]
            and row["config_name"] == spec["config_name"]
            and row["detector_head"] == spec["detector_head"]
        ):
            return row
    raise ValueError(f"missing public row for {setting} seed {seed}")


def _find_fixed_row(rows: list[dict[str, str]], *, setting: str, seed: str, spec: dict[str, str]) -> dict[str, str]:
    case_name = f"{SETTING_ROWS[setting]['seed_prefix']}{seed}"
    for row in rows:
        if (
            row["setting"] == setting
            and row["case_name"] == case_name
            and row["method_family"] == spec["method_family"]
            and row["config_name"] == spec["config_name"]
            and row["candidate"] == spec["candidate"]
            and row["stap_profile"] == "Brain-SIMUS-Clin-MotionMidRobust-v0"
        ):
            return row
    raise ValueError(f"missing fixed detector row for {setting} seed {seed}")


def _build_table(public_rows: list[dict[str, str]], fixed_rows: list[dict[str, str]]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/simus_cleaner_structural_checkpoint_table.py; DO NOT EDIT BY HAND.")
    lines.append(r"\begin{center}")
    lines.append(r"\captionsetup{type=table}")
    lines.append(r"\footnotesize")
    lines.append(r"\setlength{\tabcolsep}{3pt}")

    for idx, setting in enumerate(("Mobile", "Intra-operative parenchymal")):
        spec = SETTING_ROWS[setting]
        lines.append(rf"\par\medskip\noindent\textbf{{{setting}}}\par")
        lines.append(
            rf"\smallskip\noindent Best conventional baseline: {spec['public']['label']}. Fixed detector chain: {spec['fixed']['label']}.\par\smallskip"
        )
        lines.append(r"\resizebox{\linewidth}{!}{%")
        lines.append(r"\begin{tabular}{@{}l c c c c c c@{}}")
        lines.append(r"\hline")
        lines.append(
            r"Summary & \multicolumn{3}{c}{Best conventional baseline} & \multicolumn{3}{c}{Fixed detector chain} \\"
        )
        lines.append(r"\cline{2-4} \cline{5-7}")
        lines.append(
            r" & AUC$_{\mathrm{main/bg}}$ & AUC$_{\mathrm{main/nuis}}$ & FPR$_{\mathrm{nuis}}$ @ TPR$_{\mathrm{main}}=0.5$ & "
            r"AUC$_{\mathrm{main/bg}}$ & AUC$_{\mathrm{main/nuis}}$ & FPR$_{\mathrm{nuis}}$ @ TPR$_{\mathrm{main}}=0.5$ \\"
        )
        lines.append(r"\hline")
        public_seed_rows = []
        fixed_seed_rows = []
        for seed in ("127", "128"):
            public = _find_public_row(public_rows, setting=setting, seed=seed, spec=spec["public"])
            fixed = _find_fixed_row(fixed_rows, setting=setting, seed=seed, spec=spec["fixed"])
            public_seed_rows.append(public)
            fixed_seed_rows.append(fixed)
        row = [
            r"Mean [min,max] over seeds 127--128",
            _fmt_summary([r["auc_main_vs_bg"] for r in public_seed_rows]),
            _fmt_summary([r["auc_main_vs_nuisance"] for r in public_seed_rows]),
            _fmt_summary([r["fpr_nuisance_match@0p5"] for r in public_seed_rows]),
            _fmt_summary([r["auc_main_vs_bg"] for r in fixed_seed_rows]),
            _fmt_summary([r["auc_main_vs_nuisance"] for r in fixed_seed_rows]),
            _fmt_summary([r["fpr_nuisance_match@0p5"] for r in fixed_seed_rows], zero_note=True),
        ]
        lines.append(" & ".join(row) + r" \\")
        lines.append(r"\hline")
        lines.append(r"\end{tabular}")
        lines.append(r"}")
        if idx == 0:
            lines.append(r"\medskip")

    lines.append(
        r"\par\smallskip\noindent\footnotesize $^{\dagger}$Exactly zero observed nuisance detections; supported floor 1/886 (mobile) and 1/280 (intra-operative parenchymal).\par"
    )
    lines.append(
        r"\caption{Held-out SIMUS-Struct reference settings. For each evaluated structural setting, we report the best conventional baseline from the development-split baseline sweep and the strongest fixed detector chain chosen on development seeds 125--126, then evaluated unchanged on held-out seeds 127--128. Values are mean [min,max] over the two held-out seeds. AUC$_{\mathrm{main/bg}}$ measures separation of target flow from ordinary background, AUC$_{\mathrm{main/nuis}}$ measures separation of target flow from explicit nuisance structures, and FPR$_{\mathrm{nuis}}$ @ TPR$_{\mathrm{main}}=0.5$ asks how many nuisance detections survive when the detector is tuned to retain half of the target positives.}"
    )
    lines.append(r"\label{tab:accepted_v2_structural_main}")
    lines.append(r"\end{center}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate the held-out SIMUS structural reference-regime table.")
    ap.add_argument(
        "--public-csv",
        type=Path,
        default=Path("reports/simus_v2/simus_symmetric_pipeline_compare_seed125_126_to_127_128.csv"),
    )
    ap.add_argument(
        "--fixed-csv",
        type=Path,
        default=Path("reports/simus_v2/simus_structural_candidate_compare_rows.csv"),
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/paper/accepted_v2_structural_main_table.tex"),
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    public_rows = _load_rows(Path(args.public_csv))
    fixed_rows = _load_rows(Path(args.fixed_csv))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(_build_table(public_rows, fixed_rows), encoding="utf-8")
    print(f"[simus-cleaner-checkpoint] wrote {args.out_tex}")


if __name__ == "__main__":
    main()
