#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
from pathlib import Path


SETTING_ROWS = {
    "Mobile": {
        "seed_prefix": "mobile",
        "public": {
            "method_family": "hosvd",
            "config_name": "rank8_16_16_ds2_t32",
            "detector_head": "kasai",
            "label": r"HOSVD $\rightarrow$ Kasai",
        },
        "fixed": {
            "method_family": "svd_similarity",
            "config_name": "conservative_r8",
            "candidate": "unwhitened_ref",
            "label": r"Adaptive Global SVD $\rightarrow$ fixed matched-subspace",
        },
    },
    "Intra-operative parenchymal": {
        "seed_prefix": "intraop",
        "public": {
            "method_family": "hosvd",
            "config_name": "rank8_16_16_ds2_t32",
            "detector_head": "kasai",
            "label": r"HOSVD $\rightarrow$ Kasai",
        },
        "fixed": {
            "method_family": "rpca",
            "config_name": "lam1_it250_ds2_t32_r4",
            "candidate": "unwhitened_ref",
            "label": r"RPCA $\rightarrow$ fixed matched-subspace",
        },
    },
}


def _load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _fmt(x: str | float) -> str:
    value = float(x)
    if 0.999 < value < 1.0:
        return f"{value:.5f}"
    return f"{value:.3f}"


def _find_public_row(rows: list[dict[str, str]], *, setting: str, seed: str, spec: dict[str, str]) -> dict[str, str]:
    case_name = f"{SETTING_ROWS[setting]['seed_prefix']}{seed}"
    for row in rows:
        inferred_setting = "Mobile" if row["case_name"].startswith("mobile") else "Intra-operative parenchymal"
        if (
            row["split"] == "eval"
            and inferred_setting == setting
            and row["case_name"] == case_name
            and row["method_family"] == spec["method_family"]
            and row["config_name"] == spec["config_name"]
            and row["detector_head"] == spec["detector_head"]
        ):
            return row
    raise ValueError(f"missing public row for {setting} seed {seed}")


def _find_fixed_row(rows: list[dict[str, str]], *, setting: str, seed: str, spec: dict[str, str]) -> dict[str, str]:
    case_name = f"{SETTING_ROWS[setting]['seed_prefix']}{seed}"
    for row in rows:
        if (
            row["setting"] == setting
            and row["case_name"] == case_name
            and row["method_family"] == spec["method_family"]
            and row["config_name"] == spec["config_name"]
            and row["candidate"] == spec["candidate"]
            and row["stap_profile"] == "Brain-SIMUS-Clin-MotionMidRobust-v0"
        ):
            return row
    raise ValueError(f"missing fixed detector row for {setting} seed {seed}")


def _build_table(public_rows: list[dict[str, str]], fixed_rows: list[dict[str, str]]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/simus_cleaner_structural_checkpoint_table.py; DO NOT EDIT BY HAND.")
    lines.append(r"\begin{center}")
    lines.append(r"\captionsetup{type=table}")
    lines.append(r"\footnotesize")
    lines.append(r"\setlength{\tabcolsep}{4pt}")

    for idx, setting in enumerate(("Mobile", "Intra-operative parenchymal")):
        spec = SETTING_ROWS[setting]
        lines.append(rf"\par\medskip\noindent\textbf{{{setting}}}\par")
        lines.append(
            rf"\smallskip\noindent Best conventional baseline: {spec['public']['label']}. Fixed detector chain: {spec['fixed']['label']}.\par\smallskip"
        )
        lines.append(r"\begin{tabular}{@{}l c c c c c c@{}}")
        lines.append(r"\hline")
        lines.append(
            r"Seed & \multicolumn{3}{c}{Best conventional baseline} & \multicolumn{3}{c}{Fixed detector chain} \\"
        )
        lines.append(r"\cline{2-4} \cline{5-7}")
        lines.append(
            r" & AUC$_{\mathrm{main/bg}}$ & AUC$_{\mathrm{main/nuis}}$ & FPR$_{\mathrm{nuis}}$ @ TPR$_{\mathrm{main}}=0.5$ & "
            r"AUC$_{\mathrm{main/bg}}$ & AUC$_{\mathrm{main/nuis}}$ & FPR$_{\mathrm{nuis}}$ @ TPR$_{\mathrm{main}}=0.5$ \\"
        )
        lines.append(r"\hline")
        for seed in ("127", "128"):
            public = _find_public_row(public_rows, setting=setting, seed=seed, spec=spec["public"])
            fixed = _find_fixed_row(fixed_rows, setting=setting, seed=seed, spec=spec["fixed"])
            row = [
                f"Seed {seed}",
                _fmt(public["auc_main_vs_bg"]),
                _fmt(public["auc_main_vs_nuisance"]),
                _fmt(public["fpr_nuisance_match@0p5"]),
                _fmt(fixed["auc_main_vs_bg"]),
                _fmt(fixed["auc_main_vs_nuisance"]),
                _fmt(fixed["fpr_nuisance_match@0p5"]),
            ]
            lines.append(" & ".join(row) + r" \\")
        lines.append(r"\hline")
        lines.append(r"\end{tabular}")
        if idx == 0:
            lines.append(r"\medskip")

    lines.append(
        r"\caption{Held-out SIMUS-Struct reference regimes with explicit held-out seed rows. For each evaluated structural setting, we report the best conventional baseline from the development-split baseline sweep and the strongest fixed detector chain chosen on development seeds 125--126, then evaluated unchanged on held-out seeds 127--128. Seed-specific held-out values are shown directly rather than pooled summaries.}"
    )
    lines.append(r"\label{tab:accepted_v2_structural_main}")
    lines.append(r"\end{center}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Generate the held-out SIMUS structural reference-regime table.")
    ap.add_argument(
        "--public-csv",
        type=Path,
        default=Path("reports/simus_v2/simus_symmetric_pipeline_compare_seed125_126_to_127_128.csv"),
    )
    ap.add_argument(
        "--fixed-csv",
        type=Path,
        default=Path("reports/simus_v2/simus_structural_candidate_compare_rows.csv"),
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/accepted_v2_structural_main_table.tex"),
    )
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    public_rows = _load_rows(Path(args.public_csv))
    fixed_rows = _load_rows(Path(args.fixed_csv))
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(_build_table(public_rows, fixed_rows), encoding="utf-8")
    print(f"[simus-cleaner-checkpoint] wrote {args.out_tex}")


if __name__ == "__main__":
    main()
