#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

from scripts.simus_eval_structural import evaluate_structural_metrics
from sim.simus.bundle import derive_bundle_from_run


def _setting_label(run_dir: Path) -> str:
    name = run_dir.name.lower()
    if "clin_mobile" in name:
        return "Mobile"
    if "clin_intraop_parenchyma" in name:
        return "Intra-operative parenchymal"
    return run_dir.name


def _dataset_name(run_dir: Path, key: str) -> str:
    return f"{run_dir.name}_{key}"


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        raise ValueError("no rows to write")
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.write("\n")


def _format3(x: float | None) -> str:
    if x is None or not np.isfinite(float(x)):
        return "--"
    return f"{float(x):.3f}"


def _build_table(summary_rows: list[dict[str, Any]]) -> str:
    order = [
        "PD on MC--SVD residual",
        "Unwhitened ratio",
        "Whitened power",
        "Fully whitened matched-subspace detector",
    ]
    settings = ["Mobile", "Intra-operative parenchymal"]
    keyed = {(r["method_label"], r["setting"]): r for r in summary_rows}

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/simus_detector_family_ablation_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{@{}lccc ccc@{}}")
    lines.append("\\hline")
    lines.append(
        "Method & \\multicolumn{3}{c}{Mobile} & \\multicolumn{3}{c}{Intra-operative parenchymal} \\\\"
    )
    lines.append("\\cline{2-4} \\cline{5-7}")
    lines.append(
        " & AUC$_{\\mathrm{main/bg}}$ & AUC$_{\\mathrm{main/nuis}}$ & "
        "FPR$_{\\mathrm{nuis}}$ @ TPR$_{\\mathrm{main}}=0.5$ & "
        "AUC$_{\\mathrm{main/bg}}$ & AUC$_{\\mathrm{main/nuis}}$ & "
        "FPR$_{\\mathrm{nuis}}$ @ TPR$_{\\mathrm{main}}=0.5$ \\\\"
    )
    lines.append("\\hline")
    for method in order:
        row = [method]
        for setting in settings:
            item = keyed.get((method, setting), {})
            row.extend(
                [
                    _format3(item.get("auc_main_vs_bg_mean")),
                    _format3(item.get("auc_main_vs_nuisance_mean")),
                    _format3(item.get("fpr_nuisance_match_0p5_mean")),
                ]
            )
        lines.append(" & ".join(row) + " \\\\")
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Same-residual detector-family ablation on the held-out use-case-motivated SIMUS/PyMUST "
        "structural benchmark using a common MC--SVD residual and the current detector profile "
        "(Brain-SIMUS-Clin-MotionRobust-v0). Rows differ only in the downstream score head: "
        "baseline PD, the same flow-band matched-subspace ratio without whitening ($R=I$), total "
        "whitened slow-time power without Doppler band partition, and the fully whitened matched-"
        "subspace detector. Values are means over the two held-out evaluation seeds for each "
        "setting. Lower nuisance FPR at matched TPR is better.}"
    )
    lines.append("\\label{tab:simus_detector_family_ablation}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(description="Detector-family ablation on held-out SIMUS structural runs.")
    ap.add_argument(
        "--run",
        type=Path,
        action="append",
        default=None,
        help="Explicit SIMUS run directory (repeatable). Defaults to held-out mobile/intra-op seeds 127 and 128.",
    )
    ap.add_argument(
        "--out-root",
        type=Path,
        default=Path("runs/sim_eval/simus_detector_family_ablation"),
    )
    ap.add_argument(
        "--out-csv",
        type=Path,
        default=Path("reports/simus_v2/simus_detector_family_ablation.csv"),
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=Path("reports/simus_v2/simus_detector_family_ablation.json"),
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=Path("reports/simus_detector_family_ablation_table.tex"),
    )
    ap.add_argument("--stap-profile", type=str, default="Brain-SIMUS-Clin-MotionRobust-v0")
    ap.add_argument("--stap-device", type=str, default="cuda")
    ap.add_argument("--reuse-bundles", action="store_true")
    return ap.parse_args()


def main() -> None:
    args = parse_args()
    runs = args.run or [
        Path("runs/sim/simus_v2_acceptance_clin_mobile_pf_v2_phase3_seed127"),
        Path("runs/sim/simus_v2_acceptance_clin_mobile_pf_v2_phase3_seed128"),
        Path("runs/sim/simus_v2_acceptance_clin_intraop_parenchyma_pf_v3_phase3_seed127"),
        Path("runs/sim/simus_v2_acceptance_clin_intraop_parenchyma_pf_v3_phase3_seed128"),
    ]

    methods = [
        {
            "key": "pd",
            "method_label": "PD on MC--SVD residual",
            "run_stap": False,
            "bundle_overrides": {},
            "score_name": "score_pd_base.npy",
        },
        {
            "key": "unwhitened_ratio",
            "method_label": "Unwhitened ratio",
            "run_stap": True,
            "bundle_overrides": {"stap_detector_variant": "unwhitened_ratio"},
            "score_name": "score_stap_preka.npy",
        },
        {
            "key": "whitened_power",
            "method_label": "Whitened power",
            "run_stap": True,
            "bundle_overrides": {"stap_detector_variant": "whitened_power"},
            "score_name": "score_stap_preka.npy",
        },
        {
            "key": "stap",
            "method_label": "Fully whitened matched-subspace detector",
            "run_stap": True,
            "bundle_overrides": {"stap_detector_variant": "msd_ratio"},
            "score_name": "score_stap_preka.npy",
        },
    ]

    rows: list[dict[str, Any]] = []
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    for run_dir in runs:
        run_dir = Path(run_dir)
        ds = run_dir / "dataset"
        mask_h1_pf_main = np.load(ds / "mask_h1_pf_main.npy")
        mask_h0_bg = np.load(ds / "mask_h0_bg.npy")
        mask_h0_nuisance_pa = np.load(ds / "mask_h0_nuisance_pa.npy")
        mask_h1_alias_qc = np.load(ds / "mask_h1_alias_qc.npy")
        setting = _setting_label(run_dir)

        for method in methods:
            dataset_name = _dataset_name(run_dir, method["key"])
            bundle_dir = Path(args.out_root) / dataset_name
            if not args.reuse_bundles or not (bundle_dir / "meta.json").is_file():
                bundle_dir = derive_bundle_from_run(
                    run_dir=run_dir,
                    out_root=Path(args.out_root),
                    dataset_name=dataset_name,
                    stap_profile=str(args.stap_profile),
                    baseline_type="mc_svd",
                    run_stap=bool(method["run_stap"]),
                    stap_device=str(args.stap_device),
                    bundle_overrides=dict(method["bundle_overrides"]),
                    meta_extra={
                        "simus_detector_family_ablation": True,
                        "method_key": str(method["key"]),
                    },
                )
            score = np.load(Path(bundle_dir) / str(method["score_name"])).astype(np.float32, copy=False)
            metrics = evaluate_structural_metrics(
                score=score,
                mask_h1_pf_main=mask_h1_pf_main,
                mask_h0_bg=mask_h0_bg,
                mask_h0_nuisance_pa=mask_h0_nuisance_pa,
                mask_h1_alias_qc=mask_h1_alias_qc,
                fprs=[1e-4, 1e-3],
                match_tprs=[0.5],
            )
            row = {
                "run": run_dir.name,
                "setting": setting,
                "method_key": method["key"],
                "method_label": method["method_label"],
                "bundle_dir": str(bundle_dir),
                "stap_profile": str(args.stap_profile),
                "auc_main_vs_bg": metrics.get("auc_main_vs_bg"),
                "auc_main_vs_nuisance": metrics.get("auc_main_vs_nuisance"),
                "tpr_main@1e-03": metrics.get("tpr_main@1e-03"),
                "fpr_nuisance@1e-03": metrics.get("fpr_nuisance@1e-03"),
                "fpr_nuisance_match@0p5": metrics.get("fpr_nuisance_match@0p5"),
                "fpr_bg_match@0p5": metrics.get("fpr_bg_match@0p5"),
            }
            rows.append(row)
            grouped[(setting, method["method_label"])].append(row)

    summary_rows: list[dict[str, Any]] = []
    for (setting, method_label), items in sorted(grouped.items()):
        summary_rows.append(
            {
                "setting": setting,
                "method_label": method_label,
                "count": len(items),
                "auc_main_vs_bg_mean": float(np.mean([float(x["auc_main_vs_bg"]) for x in items])),
                "auc_main_vs_nuisance_mean": float(np.mean([float(x["auc_main_vs_nuisance"]) for x in items])),
                "fpr_nuisance_match_0p5_mean": float(np.mean([float(x["fpr_nuisance_match@0p5"]) for x in items])),
                "tpr_main_1e3_mean": float(np.mean([float(x["tpr_main@1e-03"]) for x in items])),
                "fpr_nuisance_1e3_mean": float(np.mean([float(x["fpr_nuisance@1e-03"]) for x in items])),
            }
        )

    _write_csv(Path(args.out_csv), rows)
    _write_json(
        Path(args.out_json),
        {
            "schema_version": "simus_detector_family_ablation.v1",
            "runs": [str(p) for p in runs],
            "stap_profile": str(args.stap_profile),
            "rows": rows,
            "summary": summary_rows,
        },
    )
    Path(args.out_tex).write_text(_build_table(summary_rows), encoding="utf-8")
    print(f"[simus-detector-family-ablation] wrote {args.out_csv}")
    print(f"[simus-detector-family-ablation] wrote {args.out_json}")
    print(f"[simus-detector-family-ablation] wrote {args.out_tex}")


if __name__ == "__main__":
    main()
