from __future__ import annotations

import csv
from pathlib import Path
from statistics import median


ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "reports" / "simus_v2"

EVAL_CSV = REPORTS / "simus_eval_functional_seed221_222_to_223_224_ec6_bgcdf_outside_headline.csv"
HEAD_CSV = REPORTS / "simus_functional_stap_head_search_seed221_222_to_223_224_ec6_bgcdf_outside_headline.csv"
OUT_TEX = ROOT / "reports" / "simus_functional_numeric_summary_table.tex"


def _read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def _q(vals: list[float], q: float) -> float:
    vals = sorted(vals)
    if len(vals) == 1:
        return vals[0]
    idx = (len(vals) - 1) * q
    lo = int(idx)
    hi = min(lo + 1, len(vals) - 1)
    frac = idx - lo
    return vals[lo] * (1.0 - frac) + vals[hi] * frac


def _fmt_med_iqr(vals: list[float], digits: int = 3, signed: bool = False) -> str:
    med = median(vals)
    q25 = _q(vals, 0.25)
    q75 = _q(vals, 0.75)
    sign = "+" if signed else ""
    return f"{med:{sign}.{digits}f} [{q25:{sign}.{digits}f},{q75:{sign}.{digits}f}]"


def main() -> None:
    eval_rows = [r for r in _read_csv(EVAL_CSV) if r["split"] == "eval"]
    head_rows = _read_csv(HEAD_CSV)

    settings = [
        ("ClinIntraOpParenchyma-Pf-v3", "Intra-operative parenchymal"),
        ("ClinMobile-Pf-v2", "Mobile"),
    ]

    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/simus_functional_numeric_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\setlength{\\tabcolsep}{4pt}")
    lines.append("\\begin{tabular}{P{2.9cm} P{3.2cm} C{1.8cm} C{2.5cm} C{2.5cm}}")
    lines.append("\\hline")
    lines.append(
        "Benchmark setting & Best end-to-end chain & \\shortstack{Matched-subspace-positive\\\\families} & "
        "\\shortstack{Median $\\Delta$ selection\\\\score [IQR]} & "
        "\\shortstack{Median $\\Delta$AUC$_{\\mathrm{act/nuis}}$\\\\(IQR)} \\\\"
    )
    lines.append("\\hline")

    for key, label in settings:
        eval_sub = [r for r in eval_rows if r["base_profile"] == key]
        head_sub = [r for r in head_rows if r["base_profile"] == key]
        best = max(eval_sub, key=lambda r: float(r["selection_score"]))
        best_chain = (
            best["pipeline_label"]
            .replace("PD-after-STAP", "PD after matched-subspace")
            .replace(" -> ", " $\\rightarrow$ ")
        )
        delta_sel = [float(r["delta_selection_eval"]) for r in head_sub]
        delta_auc_nuis = [
            float(r["stap_auc_activation_vs_nuisance_eval"]) - float(r["native_auc_activation_vs_nuisance_eval"])
            for r in head_sub
        ]
        pos = sum(v > 0.0 for v in delta_sel)
        lines.append(
            f"{label} & {best_chain} & {pos}/6 & "
            f"{_fmt_med_iqr(delta_sel, signed=True)} & {_fmt_med_iqr(delta_auc_nuis, signed=True)} \\\\"
        )

    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append(
        "\\caption{Secondary held-out functional summary on the prespecified SIMUS-Struct settings. "
        "This table uses one common background-controlled activation readout for every compared pipeline, so the rows differ only in the upstream residualizer and downstream detector head. "
        "``Best end-to-end chain'' is the strongest full held-out pipeline on that setting under that common readout. "
        "``Matched-subspace-positive families'' counts how many of the six prespecified residual families improved when the matched-subspace detector stage replaced the native conventional score on the same residual cube. "
        "``PD after matched-subspace'' denotes a power-Doppler-style summary map formed after the matched-subspace detector stage. "
        "$\\Delta$ selection score is the held-out pipeline-ranking metric used in this functional benchmark, reported as matched-subspace minus native. "
        "$\\Delta$AUC$_{\\mathrm{act/nuis}}$ is the corresponding change in separation between simulated activation and nuisance regions under the same readout. "
        "Both deltas are summarized by the median and interquartile range across the six residual families.}"
    )
    lines.append("\\label{tab:accepted_v2_functional_main}")
    lines.append("\\end{table}")
    OUT_TEX.write_text("\n".join(lines) + "\n")
    print(f"[simus-functional-table] wrote {OUT_TEX}")


if __name__ == "__main__":
    main()
