#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
import statistics
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _read_rows(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _fmt(x: float | None, digits: int = 3, *, signed: bool = False) -> str:
    if x is None or not math.isfinite(float(x)):
        return "--"
    spec = f"+.{digits}f" if signed else f".{digits}f"
    return format(float(x), spec)


def _quartiles(xs: list[float]) -> tuple[float, float, float]:
    vals = sorted(float(x) for x in xs)
    if not vals:
        raise ValueError("expected at least one value")
    med = statistics.median(vals)
    q1, q3 = statistics.quantiles(vals, n=4, method="inclusive")[0], statistics.quantiles(
        vals, n=4, method="inclusive"
    )[2]
    return float(med), float(q1), float(q3)


def _mean_ci(xs: list[float]) -> tuple[float, float, float]:
    vals = sorted(float(x) for x in xs)
    if not vals:
        raise ValueError("expected at least one value")
    mean = statistics.mean(vals)
    q1, q3 = statistics.quantiles(vals, n=40, method="inclusive")[0], statistics.quantiles(
        vals, n=40, method="inclusive"
    )[38]
    return float(mean), float(q1), float(q3)


def _score_rows(rows: list[dict[str, str]], score_key: str) -> list[dict[str, str]]:
    out = [r for r in rows if r["score_key"] == score_key]
    out.sort(key=lambda r: (int(r["block_id"]), int(r["window_index"])))
    return out


def _pair_rows(
    left_rows: list[dict[str, str]],
    right_rows: list[dict[str, str]],
) -> list[tuple[dict[str, str], dict[str, str]]]:
    left = {(int(r["block_id"]), int(r["window_index"])): r for r in left_rows}
    right = {(int(r["block_id"]), int(r["window_index"])): r for r in right_rows}
    keys = sorted(set(left) & set(right))
    return [(left[k], right[k]) for k in keys]


def _consistency_summary(
    specialist_rows: list[dict[str, str]],
    comp_rows: list[dict[str, str]],
) -> dict[str, Any]:
    pairs = _pair_rows(specialist_rows, comp_rows)
    auc_deltas = [float(a["auc"]) - float(b["auc"]) for a, b in pairs]
    fpr_deltas = [float(a["fpr_at_tpr70"]) - float(b["fpr_at_tpr70"]) for a, b in pairs]
    auc_med, auc_q1, auc_q3 = _quartiles(auc_deltas)
    fpr_med, fpr_q1, fpr_q3 = _quartiles(fpr_deltas)
    return {
        "n_windows": len(pairs),
        "auc_wins": sum(float(a["auc"]) > float(b["auc"]) for a, b in pairs),
        "fpr70_wins": sum(float(a["fpr_at_tpr70"]) < float(b["fpr_at_tpr70"]) for a, b in pairs),
        "auc_delta_median": auc_med,
        "auc_delta_q1": auc_q1,
        "auc_delta_q3": auc_q3,
        "fpr70_delta_median": fpr_med,
        "fpr70_delta_q1": fpr_q1,
        "fpr70_delta_q3": fpr_q3,
    }


def _transfer_nonzero_counts(rows: list[dict[str, str]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key in ("pd", "kasai", "matched_subspace"):
        sub = _score_rows(rows, key)
        out[key] = {
            "n_windows": len(sub),
            "nonzero_core_windows": sum(float(r["heldout_tpr_core"]) > 0.0 for r in sub),
            "mean_core_tpr": statistics.mean(float(r["heldout_tpr_core"]) for r in sub),
            "mean_shell_fpr": statistics.mean(float(r["heldout_fpr_shell"]) for r in sub),
        }
    return out


def _family_row(
    label: str,
    rows: list[dict[str, str]],
) -> dict[str, Any]:
    auc = [float(r["auc"]) for r in rows]
    tpr01 = [float(r["tpr@1e-01"]) for r in rows]
    tpr001 = [float(r["tpr@1e-02"]) for r in rows]
    tpr0001 = [float(r["tpr@1e-03"]) for r in rows]
    return {
        "label": label,
        "auc": _mean_ci(auc),
        "tpr_1e1": _mean_ci(tpr01),
        "tpr_1e2": _mean_ci(tpr001),
        "tpr_1e3": _mean_ci(tpr0001),
    }


def _build_consistency_table(payload: dict[str, Any]) -> str:
    pd_sec = payload["specialist_vs_pd"]
    kasai_sec = payload["specialist_vs_kasai"]
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/ulm7883227_pala_support_tables.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\hline")
    lines.append("Comparison & AUC wins & median $\\Delta$AUC & shell-FPR wins @70\\% core recall & median $\\Delta$ shell FPR \\\\")
    lines.append("\\hline")
    lines.append(
        "Specialist vs PD & "
        f"{pd_sec['auc_wins']}/{pd_sec['n_windows']} & "
        f"{_fmt(pd_sec['auc_delta_median'], signed=True)} [{_fmt(pd_sec['auc_delta_q1'], signed=True)},{_fmt(pd_sec['auc_delta_q3'], signed=True)}] & "
        f"{pd_sec['fpr70_wins']}/{pd_sec['n_windows']} & "
        f"{_fmt(pd_sec['fpr70_delta_median'], signed=True)} [{_fmt(pd_sec['fpr70_delta_q1'], signed=True)},{_fmt(pd_sec['fpr70_delta_q3'], signed=True)}] \\\\"
    )
    lines.append(
        "Specialist vs Kasai & "
        f"{kasai_sec['auc_wins']}/{kasai_sec['n_windows']} & "
        f"{_fmt(kasai_sec['auc_delta_median'], signed=True)} [{_fmt(kasai_sec['auc_delta_q1'], signed=True)},{_fmt(kasai_sec['auc_delta_q3'], signed=True)}] & "
        f"{kasai_sec['fpr70_wins']}/{kasai_sec['n_windows']} & "
        f"{_fmt(kasai_sec['fpr70_delta_median'], signed=True)} [{_fmt(kasai_sec['fpr70_delta_q1'], signed=True)},{_fmt(kasai_sec['fpr70_delta_q3'], signed=True)}] \\\\"
    )
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append(
        "\\caption{Window-level consistency summary for the PALA-backed ULM structural audit. "
        "Each row compares the prespecified whitened matched-subspace specialist against a conventional comparator on the same 20 audited windows. "
        "AUC wins count the number of windows for which the specialist has higher vessel-core versus shell AUC; shell-FPR wins count the number of windows for which it achieves lower shell false-positive rate at matched 70\\% vessel-core recall. "
        "Reported $\\Delta$ summaries are paired window-level medians with interquartile ranges.}"
    )
    lines.append("\\label{tab:ulm_pala_window_consistency}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def _build_family_table(payload: dict[str, Any]) -> str:
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/ulm7883227_pala_support_tables.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[H]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{lcccc}")
    lines.append("\\hline")
    lines.append("Score & AUC (H1 vs H0) & TPR@$10^{-1}$ & TPR@$10^{-2}$ & TPR@$10^{-3}$ \\\\")
    lines.append("\\hline")
    for row in payload["family_rows"]:
        auc = row["auc"]
        tpr1 = row["tpr_1e1"]
        tpr2 = row["tpr_1e2"]
        tpr3 = row["tpr_1e3"]
        lines.append(
            f"{row['label']} & "
            f"{_fmt(auc[0])} [{_fmt(auc[1])},{_fmt(auc[2])}] & "
            f"{_fmt(tpr1[0])} [{_fmt(tpr1[1])},{_fmt(tpr1[2])}] & "
            f"{_fmt(tpr2[0])} [{_fmt(tpr2[1])},{_fmt(tpr2[2])}] & "
            f"{_fmt(tpr3[0])} [{_fmt(tpr3[1])},{_fmt(tpr3[2])}] \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}")
    lines.append("}")
    lines.append(
        "\\caption{Same-residual detector-head comparison on the PALA-backed ULM structural audit. "
        "All rows use the same frozen 64-frame MC--SVD residual windows, the same localization-derived vessel-core versus shell masks, and the same SCM whitening recipe where applicable; only the downstream score head changes. "
        "Entries report window-level means with 95\\% empirical central intervals over the 20 audited windows.}"
    )
    lines.append("\\label{tab:ulm_pala_detector_heads}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Build ULM PALA-backed support tables for the paper.")
    ap.add_argument("--main-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_structural_roc.csv")
    ap.add_argument("--fixed-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_fixed.csv")
    ap.add_argument("--adaptive-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_adaptive.csv")
    ap.add_argument(
        "--transfer-csv",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_fixed_calibration_transfer.csv",
    )
    ap.add_argument(
        "--out-consistency-tex",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_window_consistency_table.tex",
    )
    ap.add_argument(
        "--out-family-tex",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_detector_heads_table.tex",
    )
    ap.add_argument(
        "--out-json",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_support_summary.json",
    )
    args = ap.parse_args()

    main_rows = _read_rows(args.main_csv)
    fixed_rows = _read_rows(args.fixed_csv)
    adaptive_rows = _read_rows(args.adaptive_csv)
    transfer_rows = _read_rows(args.transfer_csv)

    specialist_rows = _score_rows(main_rows, "matched_subspace")
    pd_rows = _score_rows(main_rows, "pd")
    kasai_rows = _score_rows(main_rows, "kasai")
    payload = {
        "specialist_vs_pd": _consistency_summary(specialist_rows, pd_rows),
        "specialist_vs_kasai": _consistency_summary(specialist_rows, kasai_rows),
        "fixed_threshold_transfer": _transfer_nonzero_counts(transfer_rows),
    }
    fixed_head_rows = _score_rows(fixed_rows, "matched_subspace")
    adaptive_head_rows = _score_rows(adaptive_rows, "matched_subspace")
    if fixed_head_rows and adaptive_head_rows:
        payload["family_rows"] = [
            _family_row("Baseline (power Doppler)", pd_rows),
            _family_row("Baseline (Kasai lag-1 magnitude)", kasai_rows),
            _family_row("Fixed matched-subspace detector", fixed_head_rows),
            _family_row("Adaptive detector", adaptive_head_rows),
            _family_row("Whitened matched-subspace specialist", specialist_rows),
        ]

    args.out_consistency_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_consistency_tex.write_text(_build_consistency_table(payload), encoding="utf-8")
    if "family_rows" in payload:
        args.out_family_tex.parent.mkdir(parents=True, exist_ok=True)
        args.out_family_tex.write_text(_build_family_table(payload), encoding="utf-8")
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
