#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _fmt(x: float | None, digits: int = 3) -> str:
    if x is None or not math.isfinite(float(x)):
        return "--"
    return format(float(x), f".{digits}f")


def _fmt_sci(x: float | None, digits: int = 1) -> str:
    if x is None or not math.isfinite(float(x)):
        return "--"
    value = float(x)
    if value == 0.0:
        return "0"
    text = format(value, f".{digits}e")
    return text.replace("e-0", "e-").replace("e+0", "e+")


def _fmt_interval(sec: dict[str, Any] | None, *, digits: int = 3) -> str:
    if not sec:
        return "--"
    c = sec.get("center")
    lo = sec.get("lo")
    hi = sec.get("hi")
    vals = [v for v in (c, lo, hi) if v is not None and math.isfinite(float(v))]
    if not vals:
        return "--"
    if max(abs(float(v)) for v in vals) < 1e-3:
        return f"{_fmt_sci(c)} [{_fmt_sci(lo)},{_fmt_sci(hi)}]"
    return f"{_fmt(c, digits)} [{_fmt(lo, digits)},{_fmt(hi, digits)}]"


def _score_row(condition: str, label: str, summary: dict[str, Any]) -> str:
    return (
        f"{condition} & {label} & "
        f"{_fmt_interval(summary.get('auc'))} & "
        f"{_fmt_interval(summary.get('tpr@1e-03'))} & "
        f"{_fmt_interval(summary.get('fpr_at_tpr50'))} \\\\"
    )


def _build_table(
    *,
    true_summary: dict[str, Any],
    translated_summary: dict[str, Any],
    permuted_summary: dict[str, Any],
) -> str:
    true_mode = ((true_summary.get("reference_design") or {}).get("mask_transform") or {}).get("mode", "none")
    shift = (translated_summary.get("reference_design") or {}).get("mask_transform") or {}
    shift_desc = f"roll ({int(shift.get('shift_y_px', 0))}, {int(shift.get('shift_x_px', 0))})"
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/ulm7883227_pala_mask_falsification_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{l l c c c}")
    lines.append("\\hline")
    lines.append("Mask condition & Score & AUC (H1 vs H0) & TPR@$10^{-3}$ & shell FPR @50\\% core recall \\\\")
    lines.append("\\hline")
    for condition, summary in [
        ("Intended masks", true_summary),
        (f"Large cyclic translation, {shift_desc}", translated_summary),
        ("Support-matched permuted masks", permuted_summary),
    ]:
        scores = summary["scores"]
        lines.append(_score_row(condition, "Baseline (power Doppler)", scores["pd"]))
        lines.append(_score_row("", "Baseline (Kasai lag-1 magnitude)", scores["kasai"]))
        lines.append(_score_row("", "Fully whitened specialist", scores["matched_subspace"]))
        lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Falsification controls for the ULM localization-derived structural audit. "
        "The first block reports the intended vessel-core versus perivascular-shell masks. "
        "The second applies a large cyclic translation to both masks without changing their size. "
        "The third redraws vessel and background labels at random inside the same support mask while preserving the per-block class counts. "
        "All rows use the same frozen 64-frame no-registration whitened profile and the same MC--SVD residual windows; only the structural masks change. "
        "The translated-mask block is a misregistration control rather than a pure chance control, because the shifted masks can still land on other vessel-rich anatomy within the same acquisition. "
        "The support-matched permutation is therefore the cleaner chance-like falsification for testing whether the reported structural signal depends on vascular alignment rather than generic score morphology.}"
    )
    lines.append("\\label{tab:ulm7883227_mask_falsification_supp}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the ULM mask falsification supplementary table.")
    ap.add_argument("--true-json", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_whitened.json")
    ap.add_argument(
        "--translated-json",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_profile_whitened_masktranslate.json",
    )
    ap.add_argument(
        "--permuted-json",
        type=Path,
        default=ROOT / "reports" / "ulm7883227_pala_profile_whitened_maskpermute.json",
    )
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=ROOT / "reports" / "companion" / "ulm7883227_pala_mask_falsification_table.tex",
    )
    args = ap.parse_args()

    out = _build_table(
        true_summary=_read_json(args.true_json),
        translated_summary=_read_json(args.translated_json),
        permuted_summary=_read_json(args.permuted_json),
    )
    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(out + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
