#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
import math
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _fmt(x: float | None, digits: int = 3) -> str:
    if x is None or not math.isfinite(float(x)):
        return "--"
    return format(float(x), f".{digits}f")


def _fmt_sci(x: float | None, digits: int = 1) -> str:
    if x is None or not math.isfinite(float(x)):
        return "--"
    value = float(x)
    if value == 0.0:
        return "0"
    text = format(value, f".{digits}e")
    return text.replace("e-0", "e-").replace("e+0", "e+")


def _fmt_interval(center: float | None, lo: float | None, hi: float | None, *, digits: int = 3) -> str:
    vals = [v for v in (center, lo, hi) if v is not None and math.isfinite(float(v))]
    if not vals:
        return "--"
    if max(abs(float(v)) for v in vals) < 1e-3:
        return f"{_fmt_sci(center)} [{_fmt_sci(lo)},{_fmt_sci(hi)}]"
    return f"{_fmt(center, digits)} [{_fmt(lo, digits)},{_fmt(hi, digits)}]"


def _score_rows(rows: list[dict[str, str]], score_key: str) -> list[dict[str, str]]:
    out = [r for r in rows if r["score_key"] == score_key]
    out.sort(key=lambda r: (int(r["block_id"]), int(r["window_index"])))
    return out


def _pair_rows(
    left_rows: list[dict[str, str]],
    right_rows: list[dict[str, str]],
) -> list[tuple[dict[str, str], dict[str, str]]]:
    left = {(int(r["block_id"]), int(r["window_index"])): r for r in left_rows}
    right = {(int(r["block_id"]), int(r["window_index"])): r for r in right_rows}
    keys = sorted(set(left) & set(right))
    return [(left[k], right[k]) for k in keys]


def _block_win_count(
    specialist_rows: list[dict[str, str]],
    comp_rows: list[dict[str, str]],
    metric: str,
    *,
    higher_is_better: bool,
) -> tuple[int, int]:
    pairs = _pair_rows(specialist_rows, comp_rows)
    spec_by_block: dict[int, list[float]] = {}
    comp_by_block: dict[int, list[float]] = {}
    for spec, comp in pairs:
        block = int(spec["block_id"])
        spec_by_block.setdefault(block, []).append(float(spec[metric]))
        comp_by_block.setdefault(block, []).append(float(comp[metric]))
    wins = 0
    blocks = sorted(set(spec_by_block) & set(comp_by_block))
    for block in blocks:
        s_mean = sum(spec_by_block[block]) / len(spec_by_block[block])
        c_mean = sum(comp_by_block[block]) / len(comp_by_block[block])
        if (s_mean > c_mean) if higher_is_better else (s_mean < c_mean):
            wins += 1
    return wins, len(blocks)


def _family_row(label: str, summary: dict[str, Any]) -> dict[str, Any]:
    return {
        "label": label,
        "auc": summary["auc"],
        "tpr_1e3": summary["tpr@1e-03"],
        "fpr_70": summary["fpr_at_tpr70"],
    }


def _build_table(payload: dict[str, Any]) -> str:
    auc_wins = payload["specialist_auc_block_wins"]
    auc_total = payload["n_blocks"]
    lines: list[str] = []
    lines.append("% AUTO-GENERATED by scripts/ulm7883227_pala_disjoint_support_table.py; DO NOT EDIT BY HAND.")
    lines.append("\\begin{table}[t]")
    lines.append("\\centering")
    lines.append("\\small")
    lines.append("\\resizebox{\\linewidth}{!}{%")
    lines.append("\\begin{tabular}{l c c c}")
    lines.append("\\hline")
    lines.append("Score & AUC (H1 vs H0) & TPR@$10^{-3}$ & shell FPR @70\\% core recall \\\\")
    lines.append("\\hline")
    for row in payload["family_rows"]:
        auc = row["auc"]
        tpr = row["tpr_1e3"]
        fpr = row["fpr_70"]
        lines.append(
            f"{row['label']} & "
            f"{_fmt_interval(auc['center'], auc['lo'], auc['hi'])} & "
            f"{_fmt_interval(tpr['center'], tpr['lo'], tpr['hi'])} & "
            f"{_fmt_interval(fpr['center'], fpr['lo'], fpr['hi'])} \\\\"
        )
    lines.append("\\hline")
    lines.append("\\end{tabular}%")
    lines.append("}")
    lines.append(
        "\\caption{Disjoint-source robustness variant of the ULM localization-derived structural audit. "
        "Localization-derived reference construction uses odd source blocks only, while scored windows come from even source blocks only, under the same frozen 64-frame no-registration profile used in the main audit. "
        "Entries report window-level means with 95\\% bootstrap intervals over the 70 evaluated windows. "
        f"At block level, the fully whitened specialist has higher AUC than PD, Kasai, fixed, and adaptive on {auc_wins['pd']}/{auc_total}, {auc_wins['kasai']}/{auc_total}, {auc_wins['fixed']}/{auc_total}, and {auc_wins['adaptive']}/{auc_total} evaluation blocks, respectively."
        "}"
    )
    lines.append("\\label{tab:ulm7883227_structural_roc_disjoint_supp}")
    lines.append("\\end{table}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Build the disjoint-source ULM support table.")
    ap.add_argument("--fixed-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_fixed_v2.csv")
    ap.add_argument("--adaptive-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_adaptive_v2.csv")
    ap.add_argument("--whitened-csv", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_whitened_v2.csv")
    ap.add_argument("--fixed-json", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_fixed_v2.json")
    ap.add_argument("--adaptive-json", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_adaptive_v2.json")
    ap.add_argument("--whitened-json", type=Path, default=ROOT / "reports" / "ulm7883227_pala_profile_disjoint_whitened_v2.json")
    ap.add_argument(
        "--out-tex",
        type=Path,
        default=ROOT / "reports" / "companion" / "ulm7883227_pala_disjoint_source_table.tex",
    )
    args = ap.parse_args()

    fixed_summary = _read_json(args.fixed_json)["scores"]
    adaptive_summary = _read_json(args.adaptive_json)["scores"]
    whitened_summary = _read_json(args.whitened_json)["scores"]

    fixed_rows = _read_rows(args.fixed_csv)
    adaptive_rows = _read_rows(args.adaptive_csv)
    whitened_rows = _read_rows(args.whitened_csv)

    specialist_rows = _score_rows(whitened_rows, "matched_subspace")
    payload = {
        "family_rows": [
            _family_row("Baseline (power Doppler)", fixed_summary["pd"]),
            _family_row("Baseline (Kasai lag-1 magnitude)", fixed_summary["kasai"]),
            _family_row("Fixed matched-subspace head", fixed_summary["matched_subspace"]),
            _family_row("Adaptive head", adaptive_summary["matched_subspace"]),
            _family_row("Fully whitened specialist", whitened_summary["matched_subspace"]),
        ],
        "specialist_auc_block_wins": {},
    }

    auc_wins_pd, n_blocks = _block_win_count(specialist_rows, _score_rows(whitened_rows, "pd"), "auc", higher_is_better=True)
    auc_wins_kasai, _ = _block_win_count(
        specialist_rows, _score_rows(whitened_rows, "kasai"), "auc", higher_is_better=True
    )
    auc_wins_fixed, _ = _block_win_count(
        specialist_rows, _score_rows(fixed_rows, "matched_subspace"), "auc", higher_is_better=True
    )
    auc_wins_adaptive, _ = _block_win_count(
        specialist_rows, _score_rows(adaptive_rows, "matched_subspace"), "auc", higher_is_better=True
    )
    payload["n_blocks"] = n_blocks
    payload["specialist_auc_block_wins"] = {
        "pd": auc_wins_pd,
        "kasai": auc_wins_kasai,
        "fixed": auc_wins_fixed,
        "adaptive": auc_wins_adaptive,
    }

    args.out_tex.parent.mkdir(parents=True, exist_ok=True)
    args.out_tex.write_text(_build_table(payload), encoding="utf-8")


if __name__ == "__main__":
    main()
