"""Helpers to build `write_acceptance_bundle` keyword arguments."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any, Sequence

import numpy as np

from sim.kwave.common import SimGeom


def build_write_acceptance_kwargs(
    args: argparse.Namespace,
    *,
    out_root: Path,
    geom: SimGeom,
    angle_sets_window: Sequence[Any],
    pulses_window: int,
    prf: float,
    seed: int,
    span_bounds: tuple[float, float],
    motion_half_span: float | None,
    debug_coords: Sequence[tuple[int, int]],
    ka_beta_bounds: tuple[float, float],
    ka_opts_extra: dict[str, Any],
    meta_extra: dict[str, Any],
    suffix: str | None,
    slow_time_offset: int | None,
    slow_time_length: int | None,
    flow_mask_default: np.ndarray | None,
    bg_mask_default: np.ndarray | None,
    micro_vessels_arr: np.ndarray | None,
    alias_vessels_arr: np.ndarray | None,
    hosvd_ranks: tuple[int, int, int] | None,
    hosvd_energy_fracs: tuple[float, float, float] | None,
    stap_conditional_mask: np.ndarray | None,
) -> dict[str, Any]:
    return {
        "out_root": out_root,
        "g": geom,
        "angle_sets": angle_sets_window,
        "pulses_per_set": pulses_window,
        "prf_hz": prf,
        "seed": seed,
        "synth_amp_jitter": float(args.synth_amp_jitter),
        "synth_phase_jitter": float(args.synth_phase_jitter),
        "synth_noise_level": float(args.synth_noise_level),
        "synth_shift_max_px": int(args.synth_shift_max_px),
        "tile_hw": (int(args.tile_h), int(args.tile_w)),
        "tile_stride": int(args.tile_stride),
        "Lt": int(args.lt),
        "diag_load": float(args.diag_load),
        "stap_cov_train_trim_q": float(args.stap_cov_trim_q),
        "cov_estimator": str(args.cov_estimator).lower(),
        "huber_c": float(args.huber_c),
        "stap_debug_samples": int(args.stap_debug_samples),
        "fd_span_mode": str(args.fd_span_mode).lower(),
        "fd_span_rel": span_bounds,
        "fd_fixed_span_hz": args.fd_fixed_span_hz,
        "constraint_mode": str(args.constraint_mode).lower(),
        "grid_step_rel": float(args.grid_step_rel),
        "fd_min_pts": int(args.fd_min_pts),
        "fd_max_pts": int(args.max_pts),
        "fd_min_abs_hz": float(args.fd_min_abs_hz),
        "msd_lambda": args.msd_lambda,
        "msd_ridge": float(args.msd_ridge),
        "msd_agg_mode": str(args.msd_agg).lower(),
        "msd_ratio_rho": float(args.msd_ratio_rho),
        "motion_half_span_rel": motion_half_span,
        "msd_contrast_alpha": args.msd_contrast_alpha,
        "stap_detector_variant": str(getattr(args, "stap_detector_variant", "msd_ratio")),
        "tile_debug_limit": args.tile_debug_limit,
        "alias_psd_select_enable": bool(args.alias_psd_select),
        "alias_psd_select_ratio_thresh": float(args.alias_psd_select_ratio),
        "alias_psd_select_bins": max(1, int(args.alias_psd_select_bins)),
        "stap_debug_tile_coords": debug_coords,
        "ka_mode": str(args.ka_mode).lower(),
        "ka_prior_path": str(args.ka_prior_path) if args.ka_prior_path else None,
        "ka_beta_bounds": ka_beta_bounds,
        "ka_kappa": float(args.ka_kappa),
        "ka_alpha": args.ka_alpha,
        "ka_target_retain_f": args.ka_target_retain_f,
        "ka_target_shrink_perp": args.ka_target_shrink_perp,
        "ka_equalize_pf_trace": args.ka_equalize_pf_trace,
        "ka_opts_extra": ka_opts_extra,
        "mvdr_load_mode": str(args.mvdr_load_mode).lower(),
        "mvdr_auto_kappa": float(args.mvdr_auto_kappa),
        "constraint_ridge": float(args.constraint_ridge),
        "stap_device": args.stap_device,
        "meta_extra": meta_extra,
        "dataset_suffix": suffix,
        "slow_time_offset": slow_time_offset,
        "slow_time_length": slow_time_length,
        "score_mode": str(args.score_mode),
        "flow_mask_mode": str(args.flow_mask_mode).lower(),
        "flow_mask_pd_quantile": float(args.flow_mask_pd_quantile),
        "flow_mask_depth_min_frac": float(args.flow_mask_depth_min_frac),
        "flow_mask_depth_max_frac": float(args.flow_mask_depth_max_frac),
        "flow_mask_erode_iters": int(args.flow_mask_erode_iters),
        "flow_mask_dilate_iters": int(args.flow_mask_dilate_iters),
        "flow_mask_min_pixels": int(args.flow_mask_min_pixels),
        "flow_mask_min_coverage_fraction": float(args.flow_mask_min_coverage_frac),
        "flow_mask_union_default": bool(args.flow_mask_union_default),
        "flow_mask_suppress_alias_depth": bool(args.flow_mask_suppress_alias_depth),
        "stap_enable": not bool(getattr(args, "stap_disable", False)),
        "stap_conditional_enable": bool(args.stap_conditional_enable),
        "stap_conditional_flow_mask": stap_conditional_mask,
        "stap_conditional_mask_tag": args.stap_conditional_mask_tag,
        "baseline_type": str(args.baseline).lower(),
        "baseline_support": str(args.baseline_support),
        "reg_enable": bool(args.reg_enable),
        "reg_method": str(args.reg_method),
        "reg_subpixel": int(args.reg_subpixel),
        "reg_reference": str(args.reg_reference),
        "svd_rank": args.svd_rank,
        "svd_energy_frac": args.svd_energy_frac,
        "rpca_enable": bool(args.rpca_enable),
        "rpca_lambda": args.rpca_lambda,
        "rpca_max_iters": int(args.rpca_max_iters),
        "flow_alias_hz": args.flow_alias_hz,
        "flow_alias_fraction": float(args.flow_alias_fraction),
        "flow_alias_depth_min_frac": args.flow_alias_depth_min_frac,
        "flow_alias_depth_max_frac": args.flow_alias_depth_max_frac,
        "flow_alias_jitter_hz": float(args.flow_alias_jitter_hz),
        "flow_doppler_min_hz": args.flow_doppler_min_hz,
        "flow_doppler_max_hz": args.flow_doppler_max_hz,
        "flow_doppler_tone_amp": float(args.flow_doppler_tone_amp),
        "flow_doppler_noise_amp": float(args.flow_doppler_noise_amp),
        "flow_doppler_noise_rho": float(args.flow_doppler_noise_rho),
        "flow_doppler_noise_mode": str(args.flow_doppler_noise_mode),
        "bg_alias_hz": args.bg_alias_hz,
        "bg_alias_fraction": float(args.bg_alias_fraction),
        "bg_alias_depth_min_frac": args.bg_alias_depth_min_frac,
        "bg_alias_depth_max_frac": args.bg_alias_depth_max_frac,
        "bg_alias_jitter_hz": float(args.bg_alias_jitter_hz),
        "bg_alias_highrank_mode": None
        if str(args.bg_alias_highrank_mode).lower() == "none"
        else str(args.bg_alias_highrank_mode),
        "bg_alias_highrank_deep_patch_coverage": float(args.bg_alias_highrank_coverage),
        "bg_alias_highrank_shallow_patch_coverage": float(args.bg_alias_highrank_shallow_coverage),
        "bg_alias_highrank_margin_px": int(args.bg_alias_highrank_margin_px),
        "bg_alias_highrank_freq_jitter_hz": float(args.bg_alias_highrank_freq_jitter_hz),
        "bg_alias_highrank_drift_step_hz": float(args.bg_alias_highrank_drift_step_hz),
        "bg_alias_highrank_drift_block_len": (
            int(args.bg_alias_highrank_drift_block_len)
            if args.bg_alias_highrank_drift_block_len is not None
            else None
        ),
        "bg_alias_highrank_pf_leak_eta": float(args.bg_alias_highrank_pf_leak_eta),
        "bg_alias_highrank_amp": float(args.bg_alias_highrank_amp),
        "flow_amp_scale": float(args.flow_amp_scale),
        "alias_amp_scale": float(args.alias_amp_scale),
        "vibration_hz": args.vibration_hz,
        "vibration_amp": float(args.vibration_amp),
        "vibration_depth_min_frac": float(args.vibration_depth_min_frac),
        "vibration_depth_decay_frac": float(args.vibration_depth_decay_frac),
        "aperture_phase_std": float(args.aperture_phase_std),
        "aperture_phase_corr_len": float(args.aperture_phase_corr_len),
        "aperture_phase_seed": int(args.aperture_phase_seed),
        "clutter_beta": float(args.clutter_beta),
        "clutter_snr_db": float(args.clutter_snr_db),
        "clutter_mode": str(args.clutter_mode),
        "clutter_rank": int(args.clutter_rank),
        "clutter_depth_min_frac": float(args.clutter_depth_min_frac),
        "clutter_depth_max_frac": float(args.clutter_depth_max_frac),
        "psd_telemetry": bool(args.psd_telemetry),
        "psd_tapers": int(args.psd_tapers),
        "psd_bandwidth": float(args.psd_bandwidth),
        "band_ratio_mode": str(args.band_ratio_mode),
        "band_ratio_tile_mode": str(args.psd_br_tile_mode),
        "band_ratio_flow_low_hz": float(args.psd_br_flow_low),
        "band_ratio_flow_high_hz": float(args.psd_br_flow_high),
        "band_ratio_alias_center_hz": float(args.psd_br_alias_center),
        "band_ratio_alias_width_hz": float(args.psd_br_alias_width),
        "feasibility_mode": str(args.feasibility_mode),
        "hosvd_spatial_downsample": int(args.hosvd_spatial_downsample),
        "hosvd_t_sub": args.hosvd_t_sub,
        "hosvd_ranks": hosvd_ranks,
        "hosvd_energy_fracs": hosvd_energy_fracs,
        "flow_mask_default": flow_mask_default,
        "bg_mask_default": bg_mask_default,
        "micro_vessels": micro_vessels_arr,
        "alias_vessels": alias_vessels_arr,
    }

